[WIP] 109 - Create Zaken relations from zaak-detail page
GemeenteUtrecht/zaakafhandelcomponent pull request #114
Opened 2020-11-09 15:53 UTC by SilviaAmAm

Related ticket: #109 

An additional form in the zaak detail page was added. In this form, the related zaak and the type of relation can be filled out.

2020-11-11 11:24 UTC, sergei-maertens requested changes

2020-11-11 11:24 UTC, sergei-maertens commented on src/zac/core/api/urls.py
> +    path("zaken", GetZakenView.as_view(), name="zaken"),
This URL name makes it seems like it's a frontend URL, probably that can be improved.

2020-11-11 11:24 UTC, sergei-maertens commented on src/zac/core/api/views.py
> +        client = service.build_client()
```suggestion
        client = Service.get_client(serializer.validated_data["main_zaak"])
```

2020-11-11 11:24 UTC, sergei-maertens commented on src/zac/core/api/views.py
> +    permission_classes = (permissions.IsAuthenticated,)
this is not sufficient, it means I can now just post whatever to this endpoint as long as I'm logged in. There should be a permission check that you can add related zaken - the permission will have to be defined in https://github.com/GemeenteUtrecht/zaakafhandelcomponent/blob/develop/src/zac/core/permissions.py

2020-11-11 11:24 UTC, sergei-maertens commented on src/zac/core/api/views.py
> +        return ZaakIdentificatieSerializer(data=self.request.query_params)
you can put this directly in the `def get` - no need for a separate method

2020-11-11 11:24 UTC, sergei-maertens commented on src/zac/core/api/views.py
> +        return Response(data=data)
a serializer for this would make more sense and keep the view itself clean:

```py
class ZaakSerializer(serializers.Serializer):
    identificatie = serializers.CharField()
    bronorganisatie = serializers.CharField()
    url = serializers.URLField()

# view:
serializer = ZaakSerializer(instance=zaken, many=True)
return Response(serializer.data)
```

2020-11-11 11:24 UTC, sergei-maertens commented on src/zac/core/services.py
> +        results = executor.map(_get_zaak, job_args)
You can _always_ derive which service/client you need from the zaak URL. This is amplifying the calls if there are multiple Zaken API services defined, because it will attempt to fetch the zaak in the other services and 404 there.

The original implementation was correct.

2020-11-11 11:24 UTC, sergei-maertens commented on src/zac/js/views/zaak-detail/AddZaakRelation.js
> +                <h1 className='page-title'>Relatie toevoegen</h1>
`h1` is not correct for page accessibility. Maybe a `span` or `div` are more appropriate.

2020-11-11 11:24 UTC, sergei-maertens commented on src/zac/js/views/zaak-detail/index.js
> +        );
There is no need for this - cache invalidation happens automatically with webhook callbacks. During development however you can't receive these callbacks, so you have to flush manually in that case.

2020-11-11 11:27 UTC, sergei-maertens commented
Functionality wise this is :+1:

2020-11-11 11:29 UTC, sergei-maertens commented on src/zac/js/views/zaak-detail/index.js
> +        );
There's one race-condition with the webhook call - you could as part of the endpoint to relate the zaak already invalidate the detail cache yourself - see `zac.core.cache.invalidate_zaak_cache`

2020-11-12 08:29 UTC, SilviaAmAm commented on src/zac/core/api/serializers.py
> +class AardRelatieChoices(DjangoChoices):
Created PR: https://github.com/maykinmedia/zgw-consumers/pull/15

2020-11-12 08:41 UTC, SilviaAmAm commented on src/zac/core/api/urls.py
> +    path("zaken", GetZakenView.as_view(), name="zaken"),
Changed it to `zaken_search`

2020-11-16 13:16 UTC, sergei-maertens requested changes

2020-11-16 13:16 UTC, sergei-maertens commented on src/zac/core/api/permissions.py
> +        return request.user.has_perm(zaken_add_relations.name)
This does not do what you think it does - the `get_zaak` function only looks it up. It does check that the ZAC itself has access to both zaken.

However, what should be checked is that the user has permission to add a relation to the main zaak. I wouldn't enforce that they must have permission to view the related zaak (at first).

This would turn the permission into:

```py
zaak = get_zaak(zaak_url=serializer.validated_data["main_zaak"])
return request.user.has_perm(zaken_add_relations.name, zaak)
```

2020-11-16 13:16 UTC, sergei-maertens commented on src/zac/core/permissions.py
> +    description="Voegen relaties tussen zaken toe.",
```suggestion
    description="Relateer andere zaken aan de (hoofd)zaak",
```

2020-11-16 14:50 UTC, sergei-maertens approved these changes

2020-11-16 15:06 UTC, merged