Added endpoints to fetch review request data from kownsl for BFF
GemeenteUtrecht/zaakafhandelcomponent pull request #149
Opened 2021-01-08 11:52 UTC by damm89

2021-01-11 11:50 UTC, sergei-maertens requested changes

2021-01-11 11:50 UTC, sergei-maertens commented on backend/src/zac/core/api/bff_urls.py
> +    ),
I think we should keep Kownsl-related things in `zac.contrib.kownsl`, so I'd move these URLs and views to that package. I'd also re-structure the URLs a bit for that:

```py
# in zac.contrib.kownsl.urls

urlpatterns += [
    path(
        "zaak-review-requests/<str:bronorganisatie>/<str:identificatie>",
        ZaakReviewRequestsView.as_view(),
        name="zaak-review-requests",
    )
]
```

Also notice that I'm condensing both endpoints into one here - see later remarks.

2021-01-11 11:50 UTC, sergei-maertens commented on backend/src/zac/core/api/serializers.py
> +        return obj.num_advices + obj.num_approvals
The serializer name gave me the impression that this would only have the `completed` field, but there's more information of course.

2021-01-11 11:50 UTC, sergei-maertens commented on backend/src/zac/core/api/serializers.py
> +            return ApprovalSerializer(obj.approvals, many=True).data
We have a case of polymorphism going on here, and I'd like that to be reflected in the API documentation. I'll have a go at this on this branch.

2021-01-11 11:50 UTC, sergei-maertens commented on backend/src/zac/core/api/views.py
> +            for rr, rr_advices, rr_approvals in zip(review_requests, _advices):
`rr_approvals` is not defined, that `zip` tuple will not match so I don't expect this to work at all.

2021-01-11 11:50 UTC, sergei-maertens commented on backend/src/zac/core/api/views.py
> +        return Response(serializer.data)
Please move this to `zac.contrib.kownsl`.

I'd also rename this as `ZaakReviewRequestsSummaryView` - as in the UI it displays both the type, number completed and number requested.

2021-01-11 11:50 UTC, sergei-maertens commented on backend/src/zac/core/api/views.py
> +        return Response(serializer.data)
Looking at the UI (current), it doesn't make sense to me to fetch all the review request data in bulk. I.e., a zaak can have multiple review requests, but if you're bringing up the detail information, you're doing it for a single one at once.

1. the URL should take an `id` or `uuid` parameter (`bronorganisatie` and `identificatie` are then not required), and that particular review request should then be retrieved from Kownsl.
2. Once that is done, you can retrieve `review_request.for_zaak` and perform the permission checks on that zaak (`GetZaakMixin` behaviour)
3. Once everything checks out, you can serialize just that single RR and not have to deal with any overhead of the review requests that don't have to be displayed (yet). I presume that will also simplify the frontend code.

2021-01-11 11:56 UTC, sergei-maertens commented on backend/src/zac/core/api/views.py
> +        return Response(serializer.data)
Come to think of it... do we even need this endpoint? What does it offer that http://localhost:8000/api/docs/#operation/kownsl_review_requests_advice_retrieve doesn't?

2021-01-11 19:04 UTC, damm89 commented on backend/src/zac/core/api/views.py
> +        return Response(serializer.data)
Still no need to pull all review requests, you're right. :-)

2021-01-11 19:04 UTC, damm89 commented on backend/src/zac/core/api/views.py
> +        return Response(serializer.data)
Yep, done.

2021-01-11 19:04 UTC, damm89 commented on backend/src/zac/core/api/serializers.py
> +            return ApprovalSerializer(obj.approvals, many=True).data
Curious as to see your solution!

2021-01-12 09:32 UTC, sergei-maertens requested changes
Looks good, couple more minor remarks to put the icing on the cake

2021-01-12 09:32 UTC, sergei-maertens commented on backend/src/zac/contrib/kownsl/api.py
> +        return Http404(f"Review request with id {uuid} does not exist.")
```suggestion
        raise Http404(f"Review request with id {uuid} does not exist.")
```

2021-01-12 09:32 UTC, sergei-maertens commented on backend/src/zac/contrib/kownsl/serializers.py
> +        fields = ("first_name", "last_name")
I'd include `username` too, because `first_name` and `last_name` can be blank, so the frontend can at least fall back to the username in that case.

2021-01-12 09:32 UTC, sergei-maertens commented on backend/src/zac/contrib/kownsl/views.py
> +        review_request.approvals = retrieve_approvals(review_request)
Small :zap: performance improvement possible by doing this in a `parallel()` executor

2021-01-12 09:33 UTC, sergei-maertens commented on backend/src/zac/core/api/serializers.py
> +            return ApprovalSerializer(obj.approvals, many=True).data
Hope to get to it today... but it's not the most urgent thing so not a blocker for this PR.

2021-01-13 08:30 UTC, sergei-maertens approved these changes

2021-01-13 14:21 UTC, merged