Feature/document wijzigen
GemeenteUtrecht/zaakafhandelcomponent pull request #157
Opened 2021-01-21 13:43 UTC by damm89

The client should be able to receive input, process it and request information from the D.O.C. (rebranding to dowc).

If a client tries to POST a duplicate request, the dowc returns a 409 conflict error which the ZDSClient will catch in its assertion of the create method. It will then retry a list request with filters to fetch the requested data from the dowc.

@kelvincy is fixing the buttons and responses on the frontend of the zaak-detail page.

2021-01-29 14:38 UTC, damm89 commented on backend/src/zac/core/fields.py
> +            "dowc:download-document",
```suggestion
            "core:download-document",
```

2021-01-29 14:39 UTC, damm89 reviewed
Fixed an error.

2021-01-29 20:22 UTC, damm89 commented on backend/src/zac/core/api/serializers.py
> +        label=_("ZAC document read URL"),
```suggestion
        label=_("ZAC document write URL"),
```

2021-02-01 11:16 UTC, sergei-maertens requested changes

2021-02-01 11:16 UTC, sergei-maertens commented on backend/src/zac/contrib/dowc/views.py
> +    def get_object(self) -> NoReturn:
```suggestion
    def get_object(self) -> Document:
```
with `zgw_consumers.api_models.documenten.Document`

2021-02-01 11:16 UTC, sergei-maertens commented on backend/src/zac/contrib/dowc/views.py
> +        return Response(serializer.data, status=status_code)
second return statement will never hit

2021-02-01 11:17 UTC, damm89 commented on backend/src/zac/contrib/dowc/views.py
> +        return Response(serializer.data, status=status_code)
Yep, that was the mock data mentioned in slack. :-)

2021-02-01 11:28 UTC, sergei-maertens approved these changes

2021-02-01 11:39 UTC, merged