Added to_internal_value to polymorphic serializer
GemeenteUtrecht/zaakafhandelcomponent pull request #192
Opened 2021-02-09 22:55 UTC by damm89

2021-02-10 11:51 UTC, sergei-maertens commented on backend/src/zac/camunda/api/urls.py
>      ),
I'd stick to using the same URLs:

* `GET` -> get the task data context
* `PUT` -> submit the task data

in the view you can implement `def get_serializer(...)` based on `self.request.method`, and then it should be picked up by the schema generation as well.

2021-02-15 09:32 UTC, sergei-maertens requested changes
Looks good, couple small remarks

2021-02-15 09:32 UTC, sergei-maertens commented on backend/src/zac/camunda/api/views.py
> +            400: SubmitUserTaskSerializer,
The validation error format is not exactly the same.

It's in my backlog to re-shape validation errors following the shape of https://docs.geostandaarden.nl/api/API-Strategie-ext/#error-handling.

I'd stick to the less helpful but correct `OpenApiTypes.OBJECT`, rather than a schema that doesn't match the actual response.

2021-02-15 09:32 UTC, sergei-maertens commented on backend/src/zac/camunda/select_documents/serializers.py
> +    def on_task_submission(self) -> NoReturn:
https://docs.python.org/3/library/typing.html#typing.NoReturn

```suggestion
    def on_task_submission(self) -> None:
```

2021-02-15 09:32 UTC, sergei-maertens commented on backend/src/zac/camunda/select_documents/serializers.py
> +        self.zaak_url = get_process_zaak_url(process_instance)
```suggestion
        zaak_url = get_process_zaak_url(process_instance)
```
I don't see what this variable should be assigned to `self`?

2021-02-15 09:32 UTC, sergei-maertens commented on backend/src/zac/contrib/kownsl/camunda.py
> +        return selected_documents
This block of code is repeated, would make sense to put that in a `Validator` class/function and specify that validator on the fields in the serializers.

2021-02-15 09:32 UTC, sergei-maertens commented on backend/src/zac/contrib/kownsl/camunda.py
> +        if KownslTypes.advice.lower() in self.context["task"].form_key.lower():
this looks incredibly fragile, and it's not obvious what the logic is here.

Is there no better, explicit way?

2021-02-15 09:32 UTC, sergei-maertens commented on backend/src/zac/contrib/kownsl/constants.py
> +    approval = ChoiceItem("approval", _("Accordering"))
This should just have been handled with the translations catalogue :-)

2021-02-15 09:32 UTC, sergei-maertens commented on backend/src/zac/contrib/validsign/camunda.py
> +        return selected_documents
Another candidate for the re-usable validators approach.

2021-02-15 09:32 UTC, sergei-maertens commented on backend/src/zac/contrib/validsign/camunda.py
> +    def on_task_submission(self) -> NoReturn:
```suggestion
    def on_task_submission(self) -> None:
```

2021-02-15 10:02 UTC, damm89 commented on backend/src/zac/contrib/validsign/camunda.py
> +    def on_task_submission(self) -> NoReturn:
Why not a noreturn?

2021-02-15 10:05 UTC, damm89 commented on backend/src/zac/contrib/kownsl/camunda.py
> +        if KownslTypes.advice.lower() in self.context["task"].form_key.lower():
Like a hard-coded mapping...? Not exactly sure. The review_type of the review_request is basically dependent on the form_key.

2021-02-15 13:37 UTC, sergei-maertens commented on backend/src/zac/contrib/validsign/camunda.py
> +    def on_task_submission(self) -> NoReturn:
because it returns `None`, `NoReturn` is meant for callables that don't return at all (because they only raise exceptions for example)

2021-02-15 13:44 UTC, sergei-maertens requested changes

2021-02-15 13:44 UTC, sergei-maertens commented on backend/src/zac/api/context.py
> +class ZaakContext:
this should probably inherit from `zac.camunda.user_tasks.Context`, otherwise the type hints based on `Context` base class are no longer correct :)

2021-02-16 08:40 UTC, sergei-maertens approved these changes

2021-02-16 08:40 UTC, merged