:sparkles: #182 -- create endpoint to grant zaak access
GemeenteUtrecht/zaakafhandelcomponent pull request #200
Opened 2021-02-12 11:28 UTC by annashamray

fixes #182

2021-02-15 12:01 UTC, sergei-maertens requested changes

2021-02-15 12:01 UTC, sergei-maertens commented on backend/src/zac/core/rules.py
> +    zaken_handle_access.name, can_handle_zaak_by_zaaktype | is_zaak_behandelaar
```suggestion
    zaken_handle_access.name, can_handle_zaak_by_zaaktype & is_zaak_behandelaar
```
as discussed on Slack - this was intentional

2021-02-16 10:31 UTC, annashamray commented on backend/src/zac/accounts/email.py
> +        zaak_url = request.build_absolute_uri(zaak_url)
`Sites` is added to the app and url is build differently for SPA and SSR

2021-02-16 11:47 UTC, sergei-maertens approved these changes

2021-02-16 11:47 UTC, merged