Werkvoorraad endpoints
GemeenteUtrecht/zaakafhandelcomponent pull request #204
Opened 2021-02-16 15:45 UTC by damm89

Needs further specification by @kelvincy

2021-02-18 15:44 UTC, sergei-maertens requested changes
Some polishing required :)

2021-02-18 15:44 UTC, sergei-maertens commented on backend/src/zac/core/api/permissions.py
> +            return False
not sure why this is always added? The endpoints only support GET anyway, so hitting this endpoint will return HTTP 405 Method not allowed

2021-02-18 15:44 UTC, sergei-maertens commented on backend/src/zac/werkvoorraad/serializers.py
> +    requesters = AccessRequesterSerializer(many=True)
```suggestion
    access_requests = AccessRequestSerializer(many=True)
```

nit-picky, but "access requester" makes me think about just the user behind the access request, not the access request itself. Also keep in mind if we add attributes to the access request and have to expose them in the API in the future, it would look semantically incorrect to have this keyed under `requesters`.

2021-02-18 15:44 UTC, sergei-maertens commented on backend/src/zac/werkvoorraad/serializers.py
> +    url = serializers.SerializerMethodField()
would benefit from a help text. I'd also mark it deprecated in the schema (I think that's possible via drf-spectacular), because I expect this to be removed once the UI has the interface to manage access requests.

2021-02-18 15:44 UTC, sergei-maertens commented on backend/src/zac/werkvoorraad/data.py
> +    requesters: List[AccessRequest]
```suggestion
    requests: List[AccessRequest]
```
or `access_requests` is a better name, see the serializer remarks

2021-02-18 15:44 UTC, sergei-maertens commented on backend/src/zac/werkvoorraad/serializers.py
> +    url = serializers.SerializerMethodField()
Help text + deprecation would be useful

2021-02-18 15:44 UTC, sergei-maertens commented on backend/src/zac/werkvoorraad/serializers.py
> +        fields = ("omschrijving",)
I'd rather re-use `zac.core.api.serializers.ZaakTypeSerializer`

2021-02-18 15:44 UTC, sergei-maertens commented on backend/src/zac/werkvoorraad/serializers.py
> +        )
I'd also consider using `zac.core.api.serializers.ZaakDetailSerializer` here rather than defining a new serializer. The `url` is not useful here - Kelvin can build the frontend URL using bronorganisatie + identificatie already.

2021-02-18 15:44 UTC, sergei-maertens commented on backend/src/zac/werkvoorraad/serializers.py
> +class WorkStackUserTaskSerializer(APIModelSerializer):
I'd re-use `zac.camunda.api.serializers.TaskSerializer` here and drop `url` - Kelvin can route to the relevant page I think. Possibly we need to serialize some zaak-information as well to be able to link to the zaak detail page.

2021-02-18 15:44 UTC, sergei-maertens commented on backend/src/zac/werkvoorraad/views.py
> +from rest_framework import authentication, permissions, views as drf_views
Please create a subpackage `api` for the API views, serializers etc... in `werkvoorraad`. Let's keep API views & classic Django views separated.

2021-02-18 15:44 UTC, sergei-maertens commented on backend/src/zac/werkvoorraad/views.py
> +        return Response(serializer.data)
I think you can let this inherit from `generics.ListView` and override `def get_queryset` to return the `access_requests_groups`. That should help a great deal with reducing the boilerplate & allows you to just define `serializer_class` and be done.

Alternatively, we could set up our own `List` base class.

2021-02-18 15:44 UTC, sergei-maertens commented on backend/src/zac/werkvoorraad/views.py
> +    schema_summary = _("List access requests")
I forgot to mention this, but that's a bit of code that will be removed. It's better to use `@drf_spectacular.utils.extend_schema(summary=_("..."))`

2021-02-18 18:53 UTC, damm89 commented on backend/src/zac/werkvoorraad/serializers.py
> +        fields = ("omschrijving",)
But isn't that against ZGW? Request only data you need.

2021-02-19 09:33 UTC, damm89 commented on backend/src/zac/core/api/permissions.py
> +            return False
Also not sure :-)

2021-02-21 12:17 UTC, damm89 commented on backend/src/zac/werkvoorraad/tests/test_user_tasks_endpoint.py
> +    Test the adhoc activities API endpoint.
```suggestion
    Test the user tasks workstack API endpoint.
```

2021-02-22 09:43 UTC, sergei-maertens commented on backend/src/zac/werkvoorraad/serializers.py
> +        fields = ("omschrijving",)
we're getting the data from the upstream endpoint anyway, it's part of the resource. I wouldn't say it's a violation?

2021-02-22 10:11 UTC, sergei-maertens approved these changes

2021-02-22 10:25 UTC, sergei-maertens commented
Marking as ready - if CI passes, we'll merge. If Kelvin has feedback, that can be done in a separate PR :)

2021-02-22 15:31 UTC, merged