access to zaak for connected users
GemeenteUtrecht/zaakafhandelcomponent pull request #209
Opened 2021-02-18 15:40 UTC by annashamray

2021-02-23 09:20 UTC, sergei-maertens requested changes
Stylistic changes, logically this looks solid.

2021-02-23 09:20 UTC, sergei-maertens commented on backend/src/zac/core/rules.py
> +def is_zaak_adviser(user: User, zaak: Optional[Zaak]):
```suggestion
def is_zaak_reviewer(user: User, zaak: Optional[Zaak]):
```
reviewer is the more generic form of advisor/approver

2021-02-23 12:57 UTC, damm89 reviewed
Looks good - just a question.

2021-02-23 12:57 UTC, damm89 commented on backend/src/zac/core/rules.py
> +        return False
Do you really want False? Shouldn't the predicate just be ignored? (i.e. shouldn't it rather return None)

2021-02-23 12:57 UTC, damm89 commented on backend/src/zac/core/rules.py
> +        return False
Same as below: Do you really want False? Shouldn't the predicate just be ignored? (i.e. shouldn't it rather return None)

2021-02-23 14:56 UTC, annashamray commented on backend/src/zac/contrib/kownsl/tests/test_zaak_review_requests.py
> +        # )
or, they are remnants of my desperate attempts to mate all tests work
I'll remove it

2021-02-23 14:56 UTC, annashamray commented on backend/src/zac/core/rules.py
> +        return False
I added this condition to make it consistent with other rule predicates. I think that this condition should be removed since these rules should not be applied when `zaak is None`. Perhaps this could be handled during auth refactoring,

2021-02-23 14:57 UTC, annashamray commented on backend/src/zac/core/rules.py
> +        return False
Please, take a look at my comment above

2021-02-24 08:46 UTC, sergei-maertens commented on backend/src/zac/core/rules.py
> +        return False
Thanks, makes sense, as this predicate really has no meaning without `zaak` object.

2021-02-24 08:49 UTC, sergei-maertens approved these changes

2021-02-24 08:49 UTC, merged