Feature/auth permission definition
GemeenteUtrecht/zaakafhandelcomponent pull request #228
Opened 2021-03-09 18:13 UTC by annashamray

fixes #225

2021-03-10 15:26 UTC, SilviaAmAm commented on backend/src/zac/accounts/constants.py
> +    document = ChoiceItem("document", _("document"))
This is a question rather than a comment: before the permissions were associated with zaaktypen and informatieobjecttypen, but now it's directly on zaken and documents?

2021-03-10 15:26 UTC, SilviaAmAm commented on backend/src/zac/accounts/models.py
> +    policy = JSONField(_("policy"), null=True, blank=True, default=dict)
Maybe this field should also have some help text?

2021-03-12 13:04 UTC, annashamray commented on backend/src/zac/utils/exceptions.py
> +    return ErrorList(error_list)
I agree! Thanks for adding it!

2021-03-17 09:03 UTC, sergei-maertens requested changes
The devil is in the details, but looks good!

2021-03-17 11:31 UTC, annashamray commented on backend/src/zac/accounts/permissions.py
> +        schema_yaml = yaml.dump(schema)
thanks! :)

2021-03-17 11:44 UTC, annashamray commented on backend/src/zac/accounts/query.py
> +        return self.filter(models.Q(users=user) | models.Q(auth_profiles__user=user))
Yeah, you are right, the duplication won't happen if the same permission is connected to the user directly and to the only auth profile of this user, because the user and the auth profiles are the only ones, the cartesian product won't happen. 

But if there are two auth profiles with the same permissions for the same user the duplication will happen. I'll put `distinct` and update the testcase to cover it

2021-03-18 08:50 UTC, sergei-maertens approved these changes

2021-03-18 08:52 UTC, merged