Added info url to dowc_client.create call
GemeenteUtrecht/zaakafhandelcomponent pull request #230
Opened 2021-03-10 15:01 UTC by damm89

2021-03-12 11:32 UTC, sergei-maertens requested changes

2021-03-12 11:32 UTC, sergei-maertens commented on backend/src/zac/contrib/dowc/api.py
> +        claims["user_email"] = user.email
See my other review here: https://github.com/maykinmedia/zgw-auth-backend/pull/1#pullrequestreview-610682741

2021-03-12 11:32 UTC, sergei-maertens commented on backend/src/zac/contrib/dowc/views.py
> +        referer = request.META.get("HTTP_REFERER", "")
PSA: in modern Django versions you can use [`request.headers`](https://docs.djangoproject.com/en/2.2/ref/request-response/#django.http.HttpRequest.headers)

2021-03-17 11:01 UTC, sergei-maertens requested changes

2021-03-17 11:01 UTC, sergei-maertens commented on backend/src/zac/contrib/dowc/tests/test_dowc_api.py
> +        self.assertEqual(claims["zds"], {"email": self.user.email})
```suggestion
        self.assertEqual(claims["email"], self.user.email)
```
and of course, update to gemma-zds-client 1.0 :-)

2021-03-17 12:33 UTC, damm89 commented on backend/src/zac/contrib/dowc/tests/test_dowc_api.py
> +        self.assertEqual(claims["zds"], {"email": self.user.email})
:partying_face:

2021-03-18 09:26 UTC, sergei-maertens approved these changes

2021-03-18 09:26 UTC, merged