Feature/auth permission rules
GemeenteUtrecht/zaakafhandelcomponent pull request #232
Opened 2021-03-10 17:20 UTC by annashamray

fixes #226

depends on #228, https://github.com/GemeenteUtrecht/kownsl/pull/32

2021-03-17 11:27 UTC, sergei-maertens requested changes
This is coming together nicely!

2021-03-17 11:27 UTC, sergei-maertens commented on backend/src/zac/api/permissions.py
> +            .filter(permission=self.permission)
```suggestion
            .filter(permission=self.permission.name)
```
I think

2021-03-17 11:27 UTC, sergei-maertens commented on backend/src/zac/api/permissions.py
> +            return True
```suggestion
        # first check atomic permissions - this checks both atomic permissions directly attached to the user
        # and atomic permissions defined to authorization profiles
        if permission_definitions.filter(object_url=obj.url).exists():
            return True
```

2021-03-17 11:27 UTC, sergei-maertens commented on backend/src/zac/api/permissions.py
> +            .exclude(policy={})
Since we're not dealing with atomic permissions here anymore, and `policy` can be "empty" but also `null` (see your models and review of other PR), this looks a bit odd. How are values handled that are `null`? And - if there's no `object_url`, that makes it a policy definition because of the mutual exclusivity, so shouldn't that mean that a policy MUST be entered?

```suggestion
            .filter(object_url="")
```

2021-03-17 11:27 UTC, sergei-maertens commented on backend/src/zac/api/permissions.py
> +            .all()
not needed if you already have a `.filter()` or `.exclude` call

2021-03-17 11:27 UTC, sergei-maertens commented on backend/src/zac/notifications/handlers.py
> +            # TODO should we remove permission if the rol is deleted?
Can we bundle these questions somewhere to ask them to the rest of the team? Or maybe ask the question on Slack in the general channel.

2021-03-17 14:31 UTC, annashamray commented on backend/src/zac/api/permissions.py
> +            .exclude(policy={})
you are right, thanks for explanation

2021-03-17 14:42 UTC, annashamray commented on backend/src/zac/api/permissions.py
> +            .all()
`.all()` is removed, `.exclude` is replaced with `.filter(object_url="")`

2021-03-17 14:46 UTC, annashamray commented on backend/src/zac/notifications/handlers.py
> +            # TODO should we remove permission if the rol is deleted?
I'll add this question along with future questions to #224 and I'll ask them on Friday meeting, I think there should be some introduction to the context of this question :)

2021-03-18 09:24 UTC, sergei-maertens approved these changes

2021-03-18 10:17 UTC, merged