Feature/auth endpoints meta
GemeenteUtrecht/zaakafhandelcomponent pull request #245
Opened 2021-03-17 17:40 UTC by annashamray

fixes #239

2021-03-22 08:15 UTC, damm89 commented on backend/src/zac/core/api/views.py
> +        zaaktypen = get_zaaktypen(self.request.user)
Line 32: from zac.accounts.permissions import UserPermissions

Is unused.

2021-03-22 08:20 UTC, damm89 requested changes

2021-03-22 08:20 UTC, damm89 commented on backend/src/zac/core/blueprints.py
> +from zgw_consumers.api_models.catalogi import ZaakType
Unused?

Just like line 3: import Q

2021-03-22 08:20 UTC, damm89 commented on backend/src/zac/core/views/zaken.py
> +        kwargs["zaaktypen"] = get_zaaktypen(self.request.user)
Line 14 
from zac.accounts.permissions import UserPermissions
is now unused

2021-03-22 08:20 UTC, damm89 commented on backend/src/zac/elasticsearch/drf_api/views.py
> +                self.request.user,
Same comment as above:

line 11
from zac.accounts.permissions import UserPermissions
is now unused

2021-03-22 08:20 UTC, damm89 commented on backend/src/zac/reports/views.py
> +        zaaktypen = get_zaaktypen(self.request.user)
line 11
from zac.accounts.permissions import UserPermissions

is now unused

2021-03-22 10:05 UTC, sergei-maertens approved these changes
Agree with the remarks from Daniël :)

2021-03-23 12:00 UTC, annashamray reviewed
@damm89 Thank you very much for your comments. The major code cleanning in the #255 - I do my best to remove all unused code and imports there

2021-03-23 12:00 UTC, annashamray commented on backend/src/zac/core/api/views.py
> +        zaaktypen = get_zaaktypen(self.request.user)
unused import is removed

2021-03-23 12:00 UTC, annashamray commented on backend/src/zac/core/blueprints.py
> +from zgw_consumers.api_models.catalogi import ZaakType
removed, thanks!

2021-03-23 12:00 UTC, annashamray commented on backend/src/zac/core/views/zaken.py
> +        kwargs["zaaktypen"] = get_zaaktypen(self.request.user)
removed!

2021-03-23 12:00 UTC, annashamray commented on backend/src/zac/elasticsearch/drf_api/views.py
> +                self.request.user,
removed

2021-03-23 12:00 UTC, annashamray commented on backend/src/zac/reports/views.py
> +        zaaktypen = get_zaaktypen(self.request.user)
also removed

2021-03-23 13:03 UTC, merged