Feature/auth endpoints core
GemeenteUtrecht/zaakafhandelcomponent pull request #249
Opened 2021-03-18 10:55 UTC by annashamray

fixes #240

2021-03-24 09:04 UTC, damm89 requested changes

2021-03-24 09:04 UTC, damm89 commented on backend/src/zac/api/permissions.py
>      def has_object_permission(self, request, view, obj):
I know this was done in an earlier PR, so it kinda sucks I didn't pick up on it then but line 100 seems a bit opaque in what you're actually querying. Wouldn't it be nicer if the permission_definitions queryset had a method attached that would get all blueprint permissions (i.e., do the filter behind the scenes)?

2021-03-24 09:04 UTC, damm89 commented on backend/src/zac/api/permissions.py
> +
I think PEP 8 states this should probably be rewritten as:

```suggestion
        if not super().has_permission(request, view):
            return False

```

2021-03-24 09:06 UTC, damm89 commented
Very nice btw. It's like wearing new shoes when I see all the new and improved DefinitionBasePermissions & ZaakDefinitionPermissions flying around.

2021-03-24 09:36 UTC, SilviaAmAm approved these changes

2021-03-24 17:05 UTC, sergei-maertens approved these changes

2021-03-25 16:15 UTC, annashamray commented
@damm89 Thank you very much, I'm happy that now everything is getting more sense

2021-03-25 16:15 UTC, merged