Feature/auth endpoints other
GemeenteUtrecht/zaakafhandelcomponent pull request #251
Opened 2021-03-18 15:25 UTC by annashamray

fixes #248

2021-03-24 09:43 UTC, SilviaAmAm approved these changes

2021-03-26 08:22 UTC, sergei-maertens requested changes

2021-03-26 08:22 UTC, sergei-maertens commented on backend/src/zac/contrib/dowc/permissions.py
> +    permission = zaken_download_documents.name
according to the type hint, this should be:

```suggestion
    permission = zaken_download_documents
```

2021-03-26 08:27 UTC, sergei-maertens approved these changes

2021-03-26 08:53 UTC, merged