Fixed a 'major' lack of functionality in user task submission - hope …
GemeenteUtrecht/zaakafhandelcomponent pull request #257
Opened 2021-03-19 15:57 UTC by damm89

…this works now.

2021-03-22 10:10 UTC, sergei-maertens requested changes
Looks okay, but I'm not sure if this is a problem in the base class or this specific user task serializer?

I'd also like to see some regression tests that fail without this patch and pass with the patch.

2021-03-22 10:10 UTC, sergei-maertens commented on backend/src/zac/camunda/api/serializers.py
> +
Shouldn't this return `data`?

2021-03-22 10:10 UTC, sergei-maertens commented on backend/src/zac/camunda/api/serializers.py
> +        self.get_mapped_serializer().is_valid(raise_exception=raise_exception)
I'd expect this to be the job of the `PolymorphicSerializer` base class, no?

2021-03-22 15:48 UTC, damm89 commented
> Looks okay, but I'm not sure if this is a problem in the base class or this specific user task serializer?
> 
> I'd also like to see some regression tests that fail without this patch and pass with the patch.

Basically the only problem was that the ChoiceField for the form key was throwing validation errors...

2021-03-24 16:57 UTC, sergei-maertens approved these changes

2021-03-24 16:57 UTC, sergei-maertens commented
I'd still expect a regression test though!

2021-03-25 14:58 UTC, sergei-maertens approved these changes

2021-03-25 14:58 UTC, merged