DocumentSelectTaskSerializer now includes document type
GemeenteUtrecht/zaakafhandelcomponent pull request #261
Opened 2021-03-22 15:19 UTC by damm89

Dependent on https://github.com/GemeenteUtrecht/ZGW/pull/738

2021-03-22 15:35 UTC, damm89 commented on backend/src/zac/core/camunda/select_documents/serializers.py
> +        child=serializers.URLField,
```suggestion
```

2021-03-22 15:36 UTC, damm89 commented on backend/src/zac/core/camunda/select_documents/serializers.py
> +        child=serializers.URLField,
```suggestion
    document_type = serializers.ChoiceField(
```

2021-03-29 08:39 UTC, sergei-maertens requested changes

2021-03-29 08:39 UTC, sergei-maertens commented on backend/src/zac/core/api/views.py
> -
PEP 257 asks you to format docstrings like this:

```
A short summary, preferably < 70-ish characters.

A more elaborate description, following a blank line.
```

This has an impact on how editors, documentation-generation tools etc. show class/function documentation.

2021-03-29 08:39 UTC, sergei-maertens commented on backend/src/zac/core/camunda/select_documents/serializers.py
> +        valid_eiots = [iot["url"] for iot in results]
This is not the set restricted to the zaaktype - for that you need to check `zaaktype.informatieobjecttypen` (see https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/catalogi-api/1.0.0/src/openapi.yaml#operation/zaaktype_read)

2021-03-29 10:11 UTC, damm89 commented on backend/src/zac/core/api/views.py
> -
Accidentally edited this!

2021-03-29 15:15 UTC, damm89 commented on backend/src/zac/core/camunda/select_documents/serializers.py
> +        valid_eiots = [iot["url"] for iot in results]
Good catch

2021-03-30 07:35 UTC, sergei-maertens approved these changes
I'm expecting some rework once Kelvin gets started with this, since it's not clear for him now which informatieobjecttypen should be shown in the UI and which don't.

https://zac-test.utrechtproeftuin.nl/api/docs/#operation/core_document_types_list is the closest we have, but not sufficient, because we should support `zaaktype` querystring here as well, and pass `zaaktype` to the frontend so it can be used to query.

2021-03-30 11:17 UTC, merged