Feature/task assignee
GemeenteUtrecht/zaakafhandelcomponent pull request #262
Opened 2021-03-22 15:46 UTC by damm89

2021-03-23 15:01 UTC, annashamray reviewed
Nice work!

2021-03-23 15:01 UTC, annashamray commented on backend/src/zac/camunda/tests/test_set_task_assignee.py
> +            self.assertIn("delegate", m.last_request.url)
Could you also add a test when `task` is not found?

2021-03-24 08:34 UTC, damm89 commented on backend/src/zac/camunda/api/views.py
> +            raise exceptions.NotFound(
Yeah tough one. If you think it's better, I'll take your word for it. :)

2021-03-24 08:39 UTC, damm89 commented on backend/src/zac/camunda/tests/test_set_task_assignee.py
> +            self.assertIn("delegate", m.last_request.url)
You got it!

2021-03-24 10:55 UTC, annashamray approved these changes

2021-03-24 13:48 UTC, sergei-maertens requested changes

2021-03-24 13:48 UTC, sergei-maertens commented on backend/src/zac/camunda/api/views.py
> +        print("LOL")
```suggestion
```

2021-03-24 13:48 UTC, sergei-maertens commented on backend/src/zac/camunda/api/views.py
> +        return task
Would put this on the serializer as a validation step.

2021-03-24 14:44 UTC, sergei-maertens approved these changes

2021-03-24 15:50 UTC, merged