Allows for editing of document confidentiality within a case
GemeenteUtrecht/zaakafhandelcomponent pull request #280
Opened 2021-04-02 09:00 UTC by damm89

2021-04-12 09:07 UTC, sergei-maertens requested changes
#281 was merged, which affects this PR quite a bit, sorry for that :/

can you rebase on main & adapt the tests to make use of the new authorizations system?

2021-04-12 09:07 UTC, sergei-maertens commented on backend/src/zac/core/api/views.py
> +                )
this looks like it should be in a `*Permission` class implementation, not in the view itself.

```py
permission_classes = (permissions.IsAuthenticated & CanReadOrUpdateZaken, CanUpdateDocumenten)
```

and then in `CanUpdateDocumenten`

```py
class CanUpdateDocumenten(...):
    def has_permission(self, request, view):
        zaak = view.get_object()
        documents, gone = get_documenten(zaak)

        for doc in documents:
        if not self.has_object_permission(request, view, doc):
            return False
```

something like that?

2021-04-12 09:07 UTC, sergei-maertens commented on backend/src/zac/core/services.py
> +def update_document(url: str, data: dict, request_kwargs: dict):
I wouldn't let the request_kwargs abstraction leak that far, just asking of the audit line is sufficient, and then you can do the request_kwargs w/ headers building in this function instead.
```suggestion
def update_document(url: str, data: dict, audit_line: str):
```

2021-04-13 11:21 UTC, damm89 commented on backend/src/zac/core/api/views.py
> +                )
In the proposed implementation rest_framework will loop through the permissions and try to see if a Zaak object complies and of course fail because the permission doesn't pertain to Zaken but rather Documents.

I've solved it by slightly adapting the filter_documenten_for_permissions function. Please review.

2021-04-20 16:12 UTC, annashamray requested changes
Good test coverage! I'm not familiar with dowc and how ZAC updates documents so I have several small questions and comments

2021-04-20 16:25 UTC, annashamray commented on backend/src/zac/core/views/utils.py
> +        if request.user.has_perm(permission.name, document):
The issue - https://github.com/GemeenteUtrecht/zaakafhandelcomponent/issues/295

2021-04-21 06:33 UTC, damm89 commented on backend/src/zac/contrib/dowc/views.py
> +            invalidate_document_cache(document)
It's only deleted in the DOWC, not in the DRC. Deleting the object in the DOWC will see if the document has changed and if so will update the document in the DRC.

2021-04-21 06:39 UTC, damm89 commented on backend/src/zac/core/api/views.py
> +        mapping = {"GET": ZaakDocumentSerializer, "PATCH": UpdateZaakDocumentSerializer}
I don't think it really matters to him. He checks the API docs and anticipates accordingly afaik. The rest of the data of the ZaakDocumentSerializer also isn't used in the FE when a patch is made.

2021-04-21 06:41 UTC, damm89 commented on backend/src/zac/core/api/views.py
> +        updated_documents = [document.pop("url") for document in serializer.data]
Idk :-) Maybe my previous idea of a solution used it and then I forgot to change it. I'll change it.

2021-04-21 06:45 UTC, damm89 commented on backend/src/zac/core/api/views.py
> +        updated_documents = [document.pop("url") for document in serializer.data]
Oh hang on. The request payload of the DRC isn't expecting a url key in the data.

2021-04-21 06:46 UTC, damm89 commented on backend/src/zac/core/views/utils.py
> +        if request.user.has_perm(permission.name, document):
So should I commit your change or not?

2021-04-21 15:22 UTC, annashamray approved these changes

2021-04-22 07:02 UTC, merged