FE now gets the available document types from the related case type o…
GemeenteUtrecht/zaakafhandelcomponent pull request #282
Opened 2021-04-08 08:09 UTC by damm89

…f the related case

2021-04-12 08:45 UTC, sergei-maertens requested changes

2021-04-12 08:45 UTC, sergei-maertens commented on backend/src/zac/core/camunda/select_documents/context.py
> +    informatieobjecttypen = get_informatieobjecttypen(bijdrage_zaaktype.catalogus)
can we rename `bijdrage_zaak*` to `related_zaak*`? bijdrage is one particular type of related case (out of three options), and I'd like to avoid future confusion

2021-04-19 13:57 UTC, annashamray requested changes

2021-04-19 13:57 UTC, annashamray commented on backend/src/zac/core/camunda/select_documents/context.py
> +    informatieobjecttypen = get_informatieobjecttypen(related_zaaktype.catalogus)
Now you request all available document types from the catalog where the zaaktype is located. But they could not relate to this zaaktype, so if you try to relate a document object with this type to the zaak you'll have the 400 error from openzaak. Is it what you want? 
If you only need document types related to the particular zaaktype you need to use this endpoint - https://openzaak.utrechtproeftuin.nl/catalogi/api/v1/schema/#tag/zaaktype-informatieobjecttypen

2021-04-20 07:15 UTC, damm89 commented on backend/src/zac/core/camunda/select_documents/context.py
> +    informatieobjecttypen = get_informatieobjecttypen(related_zaaktype.catalogus)
Nope, that's not what I wanted! :-) Thanks!

2021-04-20 08:53 UTC, annashamray approved these changes

2021-04-20 10:09 UTC, merged