Feature/es sorting
GemeenteUtrecht/zaakafhandelcomponent pull request #285
Opened 2021-04-12 11:30 UTC by damm89

2021-04-15 16:17 UTC, annashamray commented on backend/src/zac/elasticsearch/api.py
> +        deadline=zaak.deadline,
theoretically, this field can be changed, so please, include it also into `update_zaak_document` function in this file

2021-04-19 10:00 UTC, annashamray requested changes
Nice work! I really like how DRF ordering was integrated with ES sorting, especially processing ES text fields

2021-04-19 13:06 UTC, damm89 commented on backend/src/zac/elasticsearch/drf_api/filters.py
> +class ESOrderingFilter:
I also changed get_ordering_fields, remove_invalid_fields, get_default_ordering, get_default_valid_fields (-> get_all_fields) and then there was a bunch of stuff we're not using so I felt like I should just not inherit. :stuck_out_tongue:

2021-04-19 13:07 UTC, damm89 commented on backend/src/zac/elasticsearch/drf_api/filters.py
> +    def _add_keywords(self, ordering: List[str], view: views.APIView) -> List[str]:
Well they pertain only to this specific class and there is no need to include them in the public interface of the class. If you prefer them to be marked as part of the public interface that's fine too with me.

2021-04-19 13:15 UTC, damm89 commented on backend/src/zac/elasticsearch/drf_api/filters.py
> +                if properties.get("fields", {}).get(field.Keyword.name):
Those fields are filtered by "get_sorting_fields"  in zac.elasticsearch.drf_api.utils as they are unsortable (for now). The reason I left it in is in case "fields" is given as an empty dict/None... But not sure that makes sense now that I rethink about it. I'll change it so that it checks if 'fields' exists and is a dictionary with key "field.Keyword.name" in it. Very convoluted...

2021-04-20 09:18 UTC, annashamray commented on backend/src/zac/elasticsearch/drf_api/filters.py
> +    def _add_keywords(self, ordering: List[str], view: views.APIView) -> List[str]:
I'll leave it to you, I was just curious

2021-04-20 09:28 UTC, annashamray approved these changes

2021-04-20 10:07 UTC, merged