Adapted activity endpoint for BFF
GemeenteUtrecht/zaakafhandelcomponent pull request #290
Opened 2021-04-15 15:11 UTC by damm89

2021-04-20 08:25 UTC, damm89 commented on backend/src/zac/activities/api/viewsets.py
> +        responses={201: ActivitySerializer},
```suggestion
        responses={200: ActivitySerializer},
```

2021-04-20 13:30 UTC, annashamray requested changes

2021-04-20 13:30 UTC, annashamray commented on backend/src/zac/activities/api/serializers.py
> +    )
1. I think `CharField` + `UserValidator` can be replaced with `SlugRelatedField`, there is an example here:
https://github.com/GemeenteUtrecht/zaakafhandelcomponent/blob/ee504f500d9fe460fb603f2c633cfd1e5a20e36e/backend/src/zac/accounts/api/serializers.py#L34

2. I don't like that `assignee` attribute has different shapes (string or object) depending on HTTP method. I think displaying username should be enough, and if not we have `users` BFF endpoint to extract user details

2021-04-20 13:30 UTC, annashamray commented on backend/src/zac/activities/api/serializers.py
> +            validated_data["assignee"] = User.objects.get(username=assignee)
Was it already checked in `UserValidator` ?

2021-04-20 13:30 UTC, annashamray commented on backend/src/zac/activities/api/serializers.py
> +        return zaak_url
I think it would be nice to put this code into the separate validator in the utils and call it `ImmutableValidator` or something like this. And then we could reuse it for all fields which should not be changed in the endpoints

2021-04-20 13:30 UTC, annashamray commented on backend/src/zac/activities/api/viewsets.py
> +            instance._prefetched_objects_cache = {}
Could you please explain why you do it? And if you don't want django to cache prefetched objects why you use `prefetch_related` ?

2021-04-20 13:30 UTC, annashamray commented on backend/src/zac/activities/tests/test_api_response.py
> +        response = self.client.put(endpoint, data=data)
Why do you restrict the use of PUT method?

2021-04-20 13:59 UTC, annashamray commented
@damm89  Is https://github.com/GemeenteUtrecht/zaakafhandelcomponent/issues/287 a user story for this PR? 
If yes could you link them together, please?

2021-04-21 08:50 UTC, damm89 commented on backend/src/zac/activities/api/serializers.py
> +            validated_data["assignee"] = User.objects.get(username=assignee)
No, it can be empty

2021-04-21 09:12 UTC, damm89 commented on backend/src/zac/activities/api/serializers.py
> +    )
TIL! :-)

2021-04-21 10:27 UTC, damm89 commented on backend/src/zac/activities/tests/test_api_response.py
> +        response = self.client.put(endpoint, data=data)
There is no need to PUT right?

2021-04-21 10:30 UTC, damm89 commented on backend/src/zac/activities/api/viewsets.py
> +            instance._prefetched_objects_cache = {}
On an update they could be changed right (nested write serializer, for example)? Not really applicable in our case here, I guess, I just copied it from the update method from rest_framework. :-)

2021-04-22 10:36 UTC, annashamray commented on backend/src/zac/activities/tests/test_api_response.py
> +        response = self.client.put(endpoint, data=data)
.. yes :)

2021-04-22 10:37 UTC, annashamray approved these changes

2021-04-22 10:38 UTC, merged