Issue/auth refactored fixes
GemeenteUtrecht/zaakafhandelcomponent pull request #292
Opened 2021-04-16 14:38 UTC by annashamray

fixes #291

2021-04-16 14:53 UTC, damm89 requested changes

2021-04-16 14:53 UTC, damm89 commented on backend/src/zac/accounts/management/commands/add_blueprint_permissions_for_zaaktypen.py
> +                    policy__zaktype_omschrijving=zaaktype.omschrijving,
```suggestion
                    policy__zaaktype_omschrijving=zaaktype.omschrijving,
```

2021-04-16 14:53 UTC, damm89 commented on backend/src/zac/accounts/management/commands/add_blueprint_permissions_for_zaaktypen.py
> +                            "zaktype_omschrijving": zaaktype.omschrijving,
```suggestion
                            "zaaktype_omschrijving": zaaktype.omschrijving,
```

2021-04-19 11:10 UTC, SilviaAmAm commented on backend/src/zac/accounts/migrations/0025_migrate_to_permission_definitions.py
> +                    )
Shouldn't line 44-45 also be indented to be in the if statement?
```
for auth_profile in permission_set.authorizationprofile_set.all():
    auth_profile.permission_definitions.add(zaak_permission_definition)
```

2021-04-19 11:20 UTC, annashamray commented on backend/src/zac/accounts/migrations/0025_migrate_to_permission_definitions.py
> +                    )
You are right! Thanks for cathing it!

2021-04-19 11:23 UTC, damm89 approved these changes

2021-04-19 12:21 UTC, merged