feature/bff-upload-edited-document
GemeenteUtrecht/zaakafhandelcomponent pull request #296
Opened 2021-04-21 14:00 UTC by damm89

2021-04-23 11:01 UTC, annashamray requested changes

2021-04-23 11:01 UTC, annashamray commented on backend/src/zac/core/api/bff_urls.py
> +        name="zaak-document",
Now we have the same resource (ZaakDocument) which has GET, GET LIST, POST and PATH methods, but with different url structures.
I mean in the case of GET we need to specify `zaak.bronorganisatie` and `zaak.identificatie` in the path, and for PATCH and POST we don't need to do it despite the documents are created/updated for a particular zaak. 
It seems to break REST "uniform interface" principle.

2021-04-23 13:06 UTC, damm89 reviewed
.

2021-04-23 13:15 UTC, damm89 commented on backend/src/zac/core/api/bff_urls.py
> +        name="zaak-document",
The reason why is because I'm having some trouble with the permissions. 

Listing zaak documents checks the user's permissions regarding the `zaak` with `GetZaakMixin` and `CanReadZaken` which uses the `zaak` as `object_type`.
Creating a new document in the zaak checks the zaak permission through the `ZaakDefinitionPermission` and requires the zaak url to be provided in the serializer as `zaak`.
The permission for editing a document seems to me like it shouldn't have `zaak` as object_type but rather `document` and perhaps if a user can edit the zaak? In that case it would be better aligned.

2021-04-23 13:23 UTC, annashamray commented on backend/src/zac/core/api/bff_urls.py
> +        name="zaak-document",
I agree that for creating and updating documents the permissions should be used for `document` object_type. I'm not sure if we should add permissions to edit the zaak here, but perhaps you are right. 

I like your document permissions. Let's leave it as it is for now and return to it when @sergei-maertens is around? 
The issue for it - https://github.com/GemeenteUtrecht/zaakafhandelcomponent/issues/295

2021-04-23 14:04 UTC, annashamray requested changes

2021-04-23 14:04 UTC, annashamray commented on backend/src/zac/core/api/tests/test_manage_zaak_document.py
> +        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
could you please also check that enkelvoudiginformatieobjecten mock and zaakinformatieobjecten mock were called
and also that the request body was as expected ?

2021-04-26 07:35 UTC, damm89 commented on backend/src/zac/core/services.py
> +def relate_document_to_zaak(document_url: str, zaak_url: str) -> Dict[str, str]:
Thank you.

2021-04-26 09:31 UTC, sergei-maertens approved these changes

2021-04-26 09:32 UTC, merged