feature/dowc-error-relay
GemeenteUtrecht/zaakafhandelcomponent pull request #311
Opened 2021-05-05 08:49 UTC by damm89

2021-05-05 09:03 UTC, damm89 commented on backend/src/zac/contrib/dowc/api.py
> +                response = client.list("documenten", data=data)
```suggestion
            try:
                # We can fetch the first from the list because the
                # client will have raised an exception
                # if the status isn't as expected.
                response = client.list("documenten", data=data)[0]
```

2021-05-05 09:04 UTC, damm89 commented on backend/src/zac/contrib/dowc/views.py
> +    # authentication_classes = (authentication.SessionAuthentication,)
```suggestion
    authentication_classes = (authentication.SessionAuthentication,)
```

2021-05-05 09:04 UTC, damm89 commented on backend/src/zac/contrib/dowc/views.py
> +            self.document = factory(Document, document)
```suggestion
            self.document = find_document(bronorganisatie, identificatie, versie=versie)
```

2021-05-05 09:04 UTC, damm89 commented on backend/src/zac/contrib/dowc/views.py
> +        # Refresh cache state if valid response
```suggestion
        # Invalidate cache if valid response
```

2021-05-07 09:27 UTC, sergei-maertens requested changes

2021-05-07 09:27 UTC, sergei-maertens commented on backend/src/zac/contrib/dowc/api.py
> +        ):  # Requesting user may already have created an object dowc
not sure where/when this happens, since in the zds-client code it appears this only happens if the response cannot be parsed as json: https://github.com/VNG-Realisatie/gemma-zds-client/blob/master/zds_client/client.py#L215

2021-05-07 09:27 UTC, sergei-maertens commented on backend/src/zac/contrib/dowc/api.py
> +                # if the status isn't as expected.
ah I see, this is happening because the `create` call in DOWC does not always lead to a HTTP 201, if the thing already exists it will reply with a HTTP 200 :thinking: 

maybe we could change zds-client to accept a list of `accepted_status` to provide multiple okay statuses, and expose that through the `.create(...)` etc. methods so that you get more control about it. This code-block would then essentially become:

```py
response = client.create("documenten", data=data, expected_status=[201, 200])
```
you do lose the information on if the object was created or not (200 vs. 201), so I'm not too sure about this approach.

2021-05-07 09:27 UTC, sergei-maertens commented on backend/src/zac/contrib/dowc/api.py
> +            return err.args[0], status.HTTP_400_BAD_REQUEST
this I would turn into a custom exception instead:

```py
raise DOWCCreateError(err.args[0]) from err
```

instead of having different return types.

2021-05-07 09:27 UTC, sergei-maertens commented on backend/src/zac/contrib/dowc/views.py
> +            return Response(response, status=status_code)
This would then become:

```suggestion
        try:
            response, status_code = create_doc(request.user, document, purpose, referer)
        except DOWCCreateError as err:
            raise exceptions.ValidationError(err.args[0])
```

2021-05-10 10:38 UTC, sergei-maertens approved these changes

2021-05-10 10:38 UTC, sergei-maertens commented on backend/src/zac/contrib/dowc/api.py
> +from typing import Any, Dict, Tuple, Union
betrayed by the linter again I think, `Any` & `Union` are unused.

2021-05-10 10:41 UTC, merged