fix/more-doc-cache-issues
GemeenteUtrecht/zaakafhandelcomponent pull request #319
Opened 2021-05-14 13:51 UTC by damm89

2021-05-17 08:00 UTC, sergei-maertens requested changes
I *think* there's maybe a bug in the caching stuff still, but it's hard to understand.

2021-05-17 08:39 UTC, damm89 commented on backend/src/zac/core/services.py
> +            document_furl.args["versie"] = versie
You're right. This should fix it.
```suggestion
            document_furl.args["versie"] = document.versie
```

2021-05-17 08:40 UTC, damm89 commented on backend/src/zac/core/services.py
> +            document_furl.args["versie"] = versie
Caching sucks. :(

2021-05-18 08:23 UTC, sergei-maertens approved these changes

2021-05-18 08:23 UTC, merged