fix/cache-rollen
GemeenteUtrecht/zaakafhandelcomponent pull request #323
Opened 2021-05-19 07:48 UTC by damm89

2021-05-19 12:10 UTC, annashamray requested changes

2021-05-19 12:10 UTC, annashamray commented on backend/src/zac/core/cache.py
> -        cache.delete_many(cache_keys)
this function is also called when the notification about destroying the rol is received. I think in this case caches for particular rollen `"rol:{rol}"` should also be deleted

2021-05-19 13:45 UTC, damm89 commented on backend/src/zac/core/cache.py
> -        cache.delete_many(cache_keys)
If the rol gets destroyed, its cache will be invalidated by the function that destroys it. Should it be moved?

2021-05-19 14:01 UTC, annashamray commented on backend/src/zac/core/cache.py
> -        cache.delete_many(cache_keys)
the cache would be cleared if the rol is deleted in the ZAC. But what if it was deleted somewhere else? (like in OpenZaak admin). In this case we will know about it only via notifications

2021-05-19 18:52 UTC, damm89 commented on backend/src/zac/core/cache.py
> -        cache.delete_many(cache_keys)
You're right, thanks.

2021-05-20 07:52 UTC, sergei-maertens approved these changes
Looks fine, just fix the build before merging :-)

2021-05-21 08:58 UTC, sergei-maertens approved these changes

2021-05-25 12:24 UTC, merged