feature/search-reports
GemeenteUtrecht/zaakafhandelcomponent pull request #328
Opened 2021-06-01 15:52 UTC by damm89

2021-07-07 08:38 UTC, damm89 commented
Closes https://github.com/GemeenteUtrecht/zaakafhandelcomponent/issues/320

2021-07-07 13:20 UTC, sergei-maertens requested changes
Additionally, I think the `tablib` dependency is now unused and can be deleted!

2021-07-07 13:20 UTC, sergei-maertens commented on backend/src/zac/elasticsearch/drf_api/views.py
> +        return self.perform_search(kwargs)
This causes the following drf-spectacular warning:

```
Warning #2: SearchView: failed to obtain model through view's queryset due to raised exception. Prevent this either by setting "queryset = Model.objects.none()" on the view, having an empty fallback in get_queryset() or by using @extend_schema. (Exception: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?)
```

I would really, really like to avoid introducing _more_ warnings for schema generation. This is also semantically incorrect, as `get_queryset` implies a `models.QuerySet` instance which this is not.

It makes more sense to not use `GenericAPIView` functionality here, but rather implement `def post(...)` accordingly and make the relevant calls. It does not fit the `ModelViewSet` model, since no models are involved.

API documentation should then be done through `@extend_schema` options. I'm not sure _why_ the drf-yasg documentation needs the model, but probably we can avoid it trying to retrieve it through some explicit schema documentation.

2021-07-07 13:20 UTC, sergei-maertens commented on backend/src/zac/elasticsearch/drf_api/pagination.py
> +class ESPagination(BffPagination):
This will require a drf-spectacular plugin to modify the schema, since looking at http://localhost:8000/api/docs/#operation/search_reports_results now, the `fields` response key is not documented. You should be able to override https://github.com/encode/django-rest-framework/blob/master/rest_framework/pagination.py#L340, which is called here: https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/openapi.py#L394. We already have some extensions in `src/zac/api/drf_spectacular` so you can use that for inspiration.

2021-07-07 13:20 UTC, sergei-maertens commented on backend/src/zac/elasticsearch/drf_api/views.py
> +        return qs.filter(id__in=allowed_report_ids)
This looks a bit illogical - if you have a saved report (say, it's based on zaak-omschrijving). One day you can have matches that fit within your allowed zaaktypen, and the next day a new zaaktype was created with zaken that match but you don't have access permissions on the zaaktype, so now the entire report is no longer usable? Do I interpret that code right?

If that's the case, it'd make more sense that the report is accessible but the results are filtered based on your permissions (or even better - the report would be taken as a base query, and the permissions are consulted to apply the zaaktypen as extra constraints, which gives you the most efficient ES query).

What you _can_ do, is check if the query includes a set of zaaktypen, and check those zaaktypen for being a subset of the zaaktypen you have access to. Then you can reject permission, and not even hit elastic search because you know up-front that there will/may be invalid results. The current approach with multiple ES-hits seems a sub-optimal approach w/r to performance and expected results.

I realize that's a complex thing to build, so perhaps we need to discuss this with the business.

2021-07-07 13:20 UTC, sergei-maertens commented on backend/src/zac/elasticsearch/drf_api/views.py
> +        return super().update(request, *args, **kwargs)
Use `@extend_view_schema(foo=extend_schema(...), bar=extend_schema(...))` on the viewset instead, where `foo, bar` are the method names. It's a class decorator that decorates the underlying methods.

2021-07-07 13:20 UTC, sergei-maertens commented on backend/src/zac/elasticsearch/drf_api/views.py
> +    serializer_class = ZaakDocumentSerializer
This should be a detail action on the viewset, since it's directly tied to the same resource (`SearchReport`), something like:

```py
@action(detail=True, permission_classes=(...))
def results(self, request, *args, **kwargs):
    ...
```

with `rest_framework.decorators.action`. That will then show up properly in the API docs too & URL routing is handled via the viewset/router, see earlier comment in the `urls.py` file

2021-07-07 13:20 UTC, sergei-maertens commented on backend/src/zac/elasticsearch/tests/factories.py
> +    query = factory.LazyFunction(get_random_search_query)
please follow django's model convention in factories and put this field before the `class Meta:` declaration.

2021-07-07 13:51 UTC, damm89 commented on backend/src/zac/elasticsearch/drf_api/views.py
> +        return qs.filter(id__in=allowed_report_ids)
I did something like this before but you would need to update those zaaktypen in the database of the model whenever new zaaktypen get added to the report results.

2021-07-08 06:39 UTC, damm89 commented on backend/src/zac/elasticsearch/drf_api/urls.py
> +    ),
Works like a beast!

2021-07-08 06:40 UTC, damm89 commented on backend/src/zac/elasticsearch/drf_api/pagination.py
> +class ESPagination(BffPagination):
Thanks, I was looking for this functionality.

2021-07-08 06:46 UTC, damm89 commented on backend/src/zac/elasticsearch/drf_api/views.py
> +        return qs.filter(id__in=allowed_report_ids)
I guess the question that needs answering is: What is a report?

If reports should be reproducible for every user that access to that particular report then the current implementation stands. 

Otherwise, if reports should show results that fit the query and it's okay if the same report produces different results for users given their particular set of permissions, then we should filter out parts of the results that they don't have access to.

I just assumed the safest route would be the first definition, but you're right, this is something the team should define.

2021-07-08 08:04 UTC, sergei-maertens commented on backend/src/zac/elasticsearch/drf_api/views.py
> +        return qs.filter(id__in=allowed_report_ids)
The route to apply additional filtering based on permissions was picked as the desired one (during standup today)

2021-07-09 12:56 UTC, sergei-maertens approved these changes
nice!

2021-07-09 12:56 UTC, merged