:sparkles: #607 - Als BBV medewerker wil ik in de ZAC de zaakdetails …
GemeenteUtrecht/zaakafhandelcomponent pull request #332
Opened 2021-06-08 09:41 UTC by svenvandescheur

…kunnen wijzigen

2021-06-08 14:43 UTC, kelvincy requested changes

2021-06-08 14:43 UTC, kelvincy commented on frontend/zac-ui/libs/features/zaak-detail/src/lib/form/form.component.html
> +    <button *ngIf="edit" gu-button type="primary" size="small" class="d-inline-block mr-2 mb-2" [disabled]="!formGroup.valid">Save
Kan je `Save` wijzigen naar `Opslaan`?

2021-06-08 14:43 UTC, kelvincy commented on frontend/zac-ui/libs/features/zaak-detail/src/lib/informatie/informatie.component.ts
> +        placeholder: 'Geen toelichting',
De placeholder `Geen toelichting` mag er uit

2021-06-08 14:58 UTC, kelvincy requested changes

2021-06-08 14:58 UTC, kelvincy commented on frontend/zac-ui/libs/features/zaak-detail/src/lib/informatie/informatie.component.ts
> -        placeholder: 'Reden van wijziging',
De placeholder van `Toelichting` mag er uit, dit is `Reden`

2021-06-08 14:59 UTC, kelvincy requested changes

2021-06-08 14:59 UTC, kelvincy commented on frontend/zac-ui/libs/features/zaak-detail/src/lib/informatie/informatie.component.ts
> +        placeholder: 'Geen toelichting',
`Toelichting` is trouwens niet required

2021-06-09 07:22 UTC, svenvandescheur commented
Feedback verwerkt.

2021-06-09 08:18 UTC, kelvincy approved these changes

2021-06-10 07:20 UTC, merged