Issue/#781
GemeenteUtrecht/zaakafhandelcomponent pull request #335
Opened 2021-06-10 10:46 UTC by svenvandescheur

2021-06-11 09:16 UTC, svenvandescheur commented
Dynamisch maken op basis van open forms prototype api.

2021-06-11 15:52 UTC, svenvandescheur commented
@sergei-maertens wil jij een blik werpen op de backend?

2021-06-14 12:21 UTC, sergei-maertens requested changes

2021-06-14 12:21 UTC, sergei-maertens commented on backend/src/zac/forms/api/views.py
> +class OpenFormsFormListView(APIView):
let's avoid confusion with the real Open Forms and express clearly this is for the prototype

```suggestion
class OpenFormsProtoFormListView(APIView):
```

2021-06-14 12:21 UTC, sergei-maertens commented on backend/src/zac/forms/api/views.py
> +        },
Hrm, normally this would be introspected from serializers. It's a shame the protoype doesn't expose API docs.

I'd still rather use serializers, because when we switch to the actual Open Forms, this API documentation of the BFF will probably go out of sync with the actual implementation. Using serializers from the start will require us to update the serializers and then the docs are automatically updated as well.

Can we define:

```py
class OpenFormsProtoFormSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    name = serializers.CharField()
    slug = serializers.SlugField()
    layouts = serializers.ListField(child=serializers.CharField())
```

& then use it as `serializer_class` on the view

2021-06-14 12:21 UTC, sergei-maertens commented on backend/src/zac/forms/api/views.py
> +        return Response(definitions)
with the suggested above changes:

```suggestion
        definitions = client.get_forms()
        serializer = self.get_serializer(instance=definitions)
        return Response(serializer.data)
```

& define

```py
def get_serializer(self, **kwargs):
    return OpenFormsProtoFormSerializer(many=True, **kwargs)
```

this ensures drf-spectacular correctly picks up the `many=True`.

2021-06-14 12:21 UTC, sergei-maertens commented on backend/src/zac/forms/tests/test_api.py
> +    def test_view_report(self, mock_get_forms, mock_init):
bad copy-paste test name

2021-06-14 12:24 UTC, kelvincy requested changes

2021-06-14 12:24 UTC, kelvincy commented on frontend/zac-ui/libs/features/open-forms/src/lib/features-open-forms.component.ts
> +                        url: `https://formulieren-test.utrechtproeftuin.nl/forms/${form.slug}/`,
de url hiervan kan ook `formulieren.utrechtproeftuin.nl/forms` zijn, zonder `test`

2021-06-14 13:56 UTC, svenvandescheur commented on backend/src/zac/forms/api/views.py
> +class OpenFormsFormListView(APIView):
As discussed: use generic terminology instead.

2021-06-14 13:57 UTC, svenvandescheur commented on backend/src/zac/forms/api/views.py
> +        },
Much better indeed, I've added the Serializer.

2021-06-14 13:58 UTC, svenvandescheur commented on backend/src/zac/forms/tests/test_api.py
> +    def test_view_report(self, mock_get_forms, mock_init):
whoops

2021-06-14 13:59 UTC, svenvandescheur commented on frontend/zac-ui/libs/features/open-forms/src/lib/features-open-forms.component.ts
> +                        url: `https://formulieren-test.utrechtproeftuin.nl/forms/${form.slug}/`,
As discussed: create a development environment check function in utils based on the window location for now. I'll add an issue to investigate/implement a more solid check.

2021-06-14 14:26 UTC, kelvincy approved these changes

2021-06-14 15:07 UTC, sergei-maertens approved these changes

2021-06-14 16:00 UTC, merged