Issue/#817
GemeenteUtrecht/zaakafhandelcomponent pull request #365
Opened 2021-07-02 14:50 UTC by svenvandescheur

2021-07-06 07:19 UTC, kelvincy requested changes
Nice job refactoring the table component. Displaying and removing the user permissions also works fine!

A few comments in general:
- The "expand" arrow on the left side of the table can get cramped up at some resolutions. Maybe add some padding?
- In the component `gu-documenten` the button "Bewerken" will change on "Bewerkingen opslaan" after opening the editable file. This button change is not happening anymore with the new table. Can you have a look at that?

2021-07-06 07:19 UTC, kelvincy commented on frontend/zac-ui/libs/features/zaak-detail/src/lib/user-permissions/user-permissions.component.ts
> +                        comment: permission["comment?"]
The question mark can be removed. The value is not showing up.

2021-07-06 07:19 UTC, kelvincy commented on frontend/zac-ui/libs/shared/ui/components/src/lib/components/table/table.component.html
> +    <ng-container matColumnDef="_expandedDetail">
This is always visible, even when it's empty

2021-07-06 07:19 UTC, kelvincy commented on frontend/zac-ui/libs/shared/ui/components/src/lib/components/table/table.component.html
> +    <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
This is always visible, even when it's empty

2021-07-06 07:19 UTC, kelvincy commented on frontend/zac-ui/libs/shared/ui/components/src/lib/components/table/table.component.html
> +<table *ngIf="dataSource" class="mat-elevation-z8 table" [class.table--wrap]="wrap" mat-table matSort
I find this elevation a bit heavy

2021-07-06 07:19 UTC, kelvincy commented on frontend/zac-ui/libs/shared/ui/components/src/lib/components/table/table.component.scss
>  .table {
`mat-table` is using a different `font-family` than the rest of the body

2021-07-06 07:19 UTC, kelvincy commented on frontend/zac-ui/libs/features/zaak-detail/src/lib/user-permissions/user-permissions.component.ts
> +     * TODO: VALIDATE, DOES THIS WORK???
Works as expected :)

2021-07-06 07:19 UTC, kelvincy commented on frontend/zac-ui/libs/shared/ui/components/src/lib/components/table/table.service.ts
> +  // TODO: Consider migrating to a new table format?
Yes, I think we should allow a free form for the table cell instead of defining it with a type every time.

2021-07-06 07:39 UTC, svenvandescheur commented on frontend/zac-ui/libs/features/zaak-detail/src/lib/user-permissions/user-permissions.component.ts
> +     * TODO: VALIDATE, DOES THIS WORK???
:)

2021-07-06 15:32 UTC, svenvandescheur commented on frontend/zac-ui/libs/shared/ui/components/src/lib/components/table/table.component.html
> +<table *ngIf="dataSource" class="mat-elevation-z8 table" [class.table--wrap]="wrap" mat-table matSort
It seems to be the default, what value would you suggest?

2021-07-06 15:46 UTC, svenvandescheur commented on frontend/zac-ui/libs/shared/ui/components/src/lib/components/table/table.component.html
> +    <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
Table columns are always specified so don't need a check on it being present. When te table has no (loaded) data (yet) I think the headers should still show providing some context about data that might become available.

Do you think it's better to not show headers if there is no data (loaded/yet)?

2021-07-06 15:46 UTC, svenvandescheur commented on frontend/zac-ui/libs/features/zaak-detail/src/lib/user-permissions/user-permissions.component.ts
> +                        comment: permission["comment?"]
fixed

2021-07-06 16:03 UTC, svenvandescheur commented on frontend/zac-ui/libs/shared/ui/components/src/lib/components/table/table.component.html
> +    <ng-container matColumnDef="_expandedDetail">
It's visible to the browser, not the user. It might be better to hide it from the DOM as well (although this has performance impact) but this seems to be problematic for some reason (*ngIf doesn't respond properly, possibly due to mat-table implementation). I can investigate this. but given performance doesn't really seem to be worth the effort. Please let me now if this is a dealbreaker for you.

2021-07-06 16:05 UTC, svenvandescheur commented on frontend/zac-ui/libs/shared/ui/components/src/lib/components/table/table.component.scss
>  .table {
I tried to divert as little as possible from factory angular material styling as this is where we're migrating to. I think it would be a better idea to migrate the rest of the body as well.

2021-07-06 16:06 UTC, svenvandescheur commented on frontend/zac-ui/libs/shared/ui/components/src/lib/components/table/table.service.ts
> +  // TODO: Consider migrating to a new table format?
I think this is something out of scope for now.

2021-07-07 07:42 UTC, kelvincy commented on frontend/zac-ui/libs/shared/ui/components/src/lib/components/table/table.component.html
> +    <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
I agree. Just leave it as is then

2021-07-07 07:44 UTC, kelvincy commented on frontend/zac-ui/libs/shared/ui/components/src/lib/components/table/table.component.html
> +    <ng-container matColumnDef="_expandedDetail">
Each table row has a bit thicker bottom line because of some empty DOM elements. I think it's better to remove it if it's not used.

2021-07-07 07:45 UTC, kelvincy commented on frontend/zac-ui/libs/shared/ui/components/src/lib/components/table/table.component.html
> +<table *ngIf="dataSource" class="mat-elevation-z8 table" [class.table--wrap]="wrap" mat-table matSort
I suggest `mat-elevation-z1` for now.

2021-07-07 09:49 UTC, kelvincy approved these changes

2021-07-07 10:16 UTC, merged