Feature/email lookup
GemeenteUtrecht/zaakafhandelcomponent pull request #367
Opened 2021-07-06 13:24 UTC by damm89

2021-07-07 08:43 UTC, damm89 commented
Related to https://github.com/GemeenteUtrecht/bptl/pull/151
Fixes:

2021-07-07 13:44 UTC, sergei-maertens approved these changes

2021-07-07 13:45 UTC, sergei-maertens requested changes
@damm89 can you bring back the `include` and `exclude` parameters for the time being - this is a breaking change and I'd rather have a bit more wiggle room to update other systems that may be using this.

Please add a comment that these filter properties are deprecated!

2021-07-09 12:58 UTC, sergei-maertens approved these changes

2021-07-09 12:58 UTC, merged