Feature/hijack header
GemeenteUtrecht/zaakafhandelcomponent pull request #376
Opened 2021-07-16 14:45 UTC by annashamray

Issue - https://github.com/GemeenteUtrecht/ZGW/issues/835 (BE)

2021-07-19 07:50 UTC, sergei-maertens requested changes

2021-07-19 07:50 UTC, sergei-maertens commented on backend/src/zac/accounts/middleware.py
> +        response[self.header] = is_hijacked
```suggestion
        response[self.header] = "true" if is_hijacked else "false"
```

Let's not rely on implicit type conversions, this is also consistent with https://github.com/GemeenteUtrecht/zaakafhandelcomponent/blob/main/backend/src/zac/contrib/kownsl/views.py#L110

2021-07-19 07:50 UTC, sergei-maertens commented on backend/src/zac/api/schema.py
> +            enum=["False", "True"],
```suggestion
            enum=["false", "true"],
```

2021-07-19 09:41 UTC, damm89 commented on backend/src/zac/accounts/tests/test_hijack_header.py
> +                self.assertEqual(response[settings.HIJACK_HEADER], "True")
After @sergei-maertens' suggestions: 
```suggestion
                self.assertEqual(response[settings.HIJACK_HEADER], "true")
```

2021-07-19 09:41 UTC, damm89 commented on backend/src/zac/accounts/tests/test_hijack_header.py
> +                self.assertEqual(response[settings.HIJACK_HEADER], "False")
After @sergei-maertens' suggestions: 
```suggestion
                self.assertEqual(response[settings.HIJACK_HEADER], "false")
```

2021-07-19 09:41 UTC, damm89 approved these changes

2021-07-21 07:42 UTC, sergei-maertens requested changes
~~I don't see any changes to the `zac.conf.base` module to add the `HIJACK_HEADER` setting and it doesn't look like a default setting from Hijack either. Can you add it?~~

I need more coffee before I review code

2021-07-21 07:43 UTC, sergei-maertens approved these changes

2021-07-21 07:44 UTC, merged