[WIP] Feature #366 - Relate objects to zaak (backend)
GemeenteUtrecht/zaakafhandelcomponent pull request #377
Opened 2021-07-16 16:29 UTC by SilviaAmAm

Fixes #366

2021-07-19 08:28 UTC, sergei-maertens requested changes

2021-07-19 08:28 UTC, sergei-maertens commented on backend/src/zac/core/api/serializers.py
> +class ObjecttypeSerializer(serializers.Serializer):
You can let most of the serializers auto-inspect using https://github.com/maykinmedia/zgw-consumers/blob/master/zgw_consumers/drf/serializers.py#L20

It's very similar to DRFs built-in `ModelSerializer`

2021-07-19 08:28 UTC, sergei-maertens commented on backend/src/zac/core/api/views.py
> +        return fetch_objecttypes()
Please do not shoe-horn non-model things into Generic views/viewsets that are meant to work with models. It's confusing, since the return type is not as expected (list vs. queryset) and drf-spectacular is confused by it as well.

Better to just implement a pattern like in Open Forms: https://github.com/open-formulieren/open-forms/blob/master/src/openforms/utils/api/views.py

2021-07-27 14:19 UTC, SilviaAmAm commented on backend/src/zac/core/api/views.py
> +)
I added a tag `objects` since some of the enpoints are in the Objecttype API and one in the Zaken API

2021-08-02 15:58 UTC, merged