update atomic permission
GemeenteUtrecht/zaakafhandelcomponent pull request #386
Opened 2021-07-22 15:32 UTC by annashamray

fixes #384

2021-08-04 09:01 UTC, damm89 commented on backend/doc/authorization.rst
> +    * ``zaken:wijzigen`` - to modify the case, for example, to change the confidential level
```suggestion
    * ``zaken:wijzigen`` - to modify the case, for example, to change the confidentiality level
```

2021-08-04 09:10 UTC, damm89 commented on backend/doc/authorization.rst
> +    * ``zaken:wijzigen`` - to modify the case, for example, to change the confidential level
Some more "mierenn*kerij":

Lines 45 and 58 end in periods when none of the other ones do. 
The bullet point list starting at line 155 has sentences that end in periods but don't start with an upper case.

2021-08-04 09:39 UTC, damm89 requested changes
Please correct some of the formatting - otherwise looks good to me.

2021-08-12 07:43 UTC, sergei-maertens approved these changes

2021-08-12 07:44 UTC, merged