:sparkles: #860 - Toewijzen van advies/akkoord verplaatsen naar uitve…
GemeenteUtrecht/zaakafhandelcomponent pull request #389
Opened 2021-07-26 10:24 UTC by svenvandescheur

…ren popup, eventueel achter tab

2021-07-27 07:52 UTC, kelvincy requested changes
Looks nice with the tabs. Just a few remarks on the business logic. And should we make a wrapper component for `mat-tab`?

2021-07-27 07:52 UTC, kelvincy commented on frontend/zac-ui/libs/features/zaak-detail/src/lib/keten-processen/keten-processen.module.ts
> +    MatTabsModule,
Should we create a wrapper component for Mat Tabs?

2021-07-27 07:52 UTC, kelvincy commented on frontend/zac-ui/libs/features/zaak-detail/src/lib/keten-processen/keten-processen.component.html
> +                       [icon]="ketenProcessenService.isTaskActionableByUser(currentUser, task) ? 'edit' : null"
I should be able to assign myself to a taak, even if it's already assigned to another user.

2021-07-27 07:52 UTC, kelvincy commented on frontend/zac-ui/libs/features/zaak-detail/src/lib/keten-processen/keten-processen.component.html
> +                       [icon]="ketenProcessenService.isTaskActionableByUser(currentUser, task) ? 'edit' : null"
- Or assign it to someone else

2021-07-27 07:52 UTC, kelvincy commented on frontend/zac-ui/libs/features/zaak-detail/src/lib/keten-processen/keten-processen.component.html
> +                         [icon]="task.name !== ('Adviseren' || 'Accorderen') && ketenProcessenService.isTaskActionableByUser(currentUser, task) ? 'edit' : null"
Same here, a user should be able to re-assign a task if it's already assigned. Only exception is Adviseren en accorderen

2021-07-27 15:53 UTC, svenvandescheur commented
@kelvincy changes doorgevoerd, ik ben nog niet toegekomen aan de tabs omdat ik tegen een waarschijnlijk bug aanloop: https://github.com/angular/components/issues/21770, zou volgens mij opgelost kunnen worden met een update, kan jij daar naar kijken?

2021-08-04 13:28 UTC, kelvincy approved these changes

2021-08-04 13:28 UTC, merged