:sparkles: Assign groups to user tasks
GemeenteUtrecht/zaakafhandelcomponent pull request #400
Opened 2021-08-11 07:01 UTC by damm89

Related to https://github.com/GemeenteUtrecht/ZGW/issues/836

2021-08-17 15:19 UTC, sergei-maertens requested changes
I think it's a nasty feature in general and we have to accept the nature of this "hack".

The polymorphic serializer is a nice approach to getting some structure in the system, good idea!

2021-08-17 15:19 UTC, sergei-maertens commented on backend/src/zac/camunda/api/views.py
> +            }
This doesn't sit well, I think we should just skip this until someone from the group actually self-assigns the task.

2021-08-17 15:19 UTC, sergei-maertens commented on backend/src/zac/camunda/data.py
> +            from ..core.camunda.utils import User
that looks like a weird import, shouldn't that just be `zac.accounts.models.User`? And then probably you can lift the import to the top of the module.

2021-08-17 15:19 UTC, sergei-maertens commented on backend/src/zac/core/camunda/utils.py
> +    user_or_group, _name = name.split(":")[0], ":".join(name.split(":")[1:])
Can be simplified a bit, no?

```py
>>> "foo:bar:baz".split(":", 1)
['foo', 'bar:baz']
```

```suggestion
    user_or_group, _name = name.split(":", 1)
```

2021-08-17 15:19 UTC, sergei-maertens commented on backend/src/zac/core/camunda/utils.py
> +    if user_or_group == "group":
can we re-use the `AssigneeTypes` choices/constants instead?

2021-08-17 15:19 UTC, sergei-maertens commented on backend/src/zac/core/camunda/utils.py
> +            group = Group.objects.create(name=_name)
Not a bad idea tbh, maybe add a `logger.info(...)` statement so we can check logs for why a group was created if we ever wonder about that?

2021-08-17 15:19 UTC, sergei-maertens commented on backend/src/zac/core/services.py
> +                    # TODO: Create group roles?
I'd even go so far as to delete the `Rol` if it's a group, it makes no sense in a ZGW context.

There's a construction with "Organizational unit" that *may* be relevant, but we should check that with information architects and the rest of the team.

2021-08-18 08:30 UTC, damm89 commented on backend/src/zac/camunda/data.py
> +            from ..core.camunda.utils import User
Yep.

2021-08-18 14:37 UTC, damm89 commented on backend/src/zac/core/services.py
>  from django.core.cache import cache
```suggestion
from django.core.cache import cache
```

2021-08-19 07:45 UTC, sergei-maertens approved these changes

2021-08-19 07:46 UTC, merged