:children_crossing: #872 - Adviseren en Accorderen table verbeteren.
GemeenteUtrecht/zaakafhandelcomponent pull request #405
Opened 2021-08-13 15:40 UTC by svenvandescheur

2021-08-16 08:47 UTC, kelvincy requested changes

2021-08-16 08:47 UTC, kelvincy commented on frontend/zac-ui/libs/features/zaak-detail/src/lib/adviseren-accorderen/review-requests.service.ts
> +  getReviewRequestStatus(reviewRequestSummary: ReviewRequestSummary, reviewRequestDetails: ReviewRequestDetails): ReviewRequestStatus {
Volgens mij werkt deze niet naar behoren. Zie afbeelding. Ik heb in totaal 2 opgehaalde adviezen, maar ik zie `In afwachting` en een oranje icoon.

![Screenshot 2021-08-16 at 10 31 57](https://user-images.githubusercontent.com/14090502/129535424-135a09fb-0abb-4d94-bb9e-04cfbe43cae9.png)

2021-08-19 14:56 UTC, svenvandescheur commented
fixed

2021-08-20 07:30 UTC, kelvincy approved these changes

2021-08-20 10:01 UTC, merged