Increase index_zaken code coherence and performance
GemeenteUtrecht/zaakafhandelcomponent pull request #416
Opened 2021-08-24 07:14 UTC by damm89

Related to issue: #413.
I think the creation of elasticsearch documents should be separated from the saving and indexing of those documents. 

This is relevant for the bulk API of elasticsearch as well as making the code a little bit easier to handle (although more verbose). The creation and appending of inner docs is more explicit and the purpose of the related functions a bit more clear and aligned.

Also performance has increased by a factor ~4-5 in terms of time (from ~3000 seconds to ~700 seconds on my machine in similar circumstances).

2021-08-25 10:28 UTC, annashamray reviewed
I really like the pattern created in `elasticsearch/api.py` where you separate creating ES documents from fetching data from external APIs. It really helps with reusing components and reminds about single-responsibility principle :) 

I'll approve it when CI turns green again

2021-08-25 10:28 UTC, annashamray commented on backend/src/zac/elasticsearch/api.py
> +) -> List[ZaakObjectDocument]:
Some nitpicking: `create_zaakobjecten_document` and `create_rol_document` are not quite consistent with each other, since the first function creates the list of documents, and the latter - only one document. 

It would be nice if they have the same structure, cause `rollen` and `zaakobjecten` documents have the similar shape

2021-08-25 10:28 UTC, annashamray commented on backend/src/zac/elasticsearch/management/commands/index_zaken.py
> +        ]
```suggestion
        unfetched_zaaktypen = {
            zaak.zaaktype for zaak in zaken if isinstance(zaak.zaaktype, str)
        }
```

2021-08-25 12:39 UTC, damm89 commented on backend/src/zac/elasticsearch/api.py
> +) -> List[ZaakObjectDocument]:
yes, good one

2021-08-30 08:57 UTC, sergei-maertens requested changes

2021-08-30 08:57 UTC, sergei-maertens commented on backend/src/zac/elasticsearch/management/commands/index_zaken.py
> +    def zaakdocumenten_generator(self, zaken: List[Zaak]) -> List[ZaakDocument]:
```suggestion
    def zaakdocumenten_generator(self, zaken: List[Zaak]) -> Iterator[ZaakDocument]:
```

2021-08-30 08:57 UTC, sergei-maertens commented on backend/src/zac/elasticsearch/management/commands/index_zaken.py
> +        count = ZaakDocument.search().count()
isn't this limited to 1000 by default? Unless it optimizes it under the hood to do the equivalent of a `SELECT COUNT(*)`

2021-08-30 12:50 UTC, sergei-maertens commented on backend/src/zac/elasticsearch/management/commands/index_zaken.py
> +        count = ZaakDocument.search().count()
I don't know _how_, but it seems fine:

```
>>> from zac.elasticsearch.searches import *
>>> ZaakDocument
<class 'zac.elasticsearch.documents.ZaakDocument'>
>>> ZaakDocument.search().count()
2500
```

2021-08-30 12:59 UTC, sergei-maertens approved these changes

2021-08-30 15:49 UTC, merged