Feature/fe auth profiles
GemeenteUtrecht/zaakafhandelcomponent pull request #431
Opened 2021-09-07 14:02 UTC by kelvincy

2021-09-09 07:21 UTC, svenvandescheur commented on frontend/zac-ui/libs/features/auth-profiles/README.md
> +Run `nx test features-auth-profiles` to execute the unit tests.
curiosity: does this actually work?

2021-09-09 07:44 UTC, svenvandescheur requested changes
Looking good but some small remarks.

2021-09-09 07:44 UTC, svenvandescheur commented on frontend/zac-ui/libs/features/auth-profiles/src/lib/auth-profiles/add-auth-profile/add-auth-profile.component.ts
> + * Add authorisation profile form
Can we improve the documentation here?

2021-09-09 07:44 UTC, svenvandescheur commented on frontend/zac-ui/libs/features/auth-profiles/src/lib/auth-profiles/add-auth-profile/add-auth-profile.component.ts
> +  get authProfileNameControl() {
I like to adhere to a standard way of organising code in components, in newer components I make a start (see: zaak-object-search.component.ts). Is this something we want to continue throughout the project?

2021-09-09 07:44 UTC, svenvandescheur commented on frontend/zac-ui/libs/features/auth-profiles/src/lib/auth-profiles/auth-profiles.component.ts
> + * Displays authentication profiles.
Can we improve documentation here?

2021-09-09 07:44 UTC, svenvandescheur commented on frontend/zac-ui/libs/features/auth-profiles/src/lib/features-auth-profiles.component.ts
> +@Component({
Can we improve documentation here?

2021-09-09 07:44 UTC, svenvandescheur commented on frontend/zac-ui/libs/features/auth-profiles/src/lib/roles/roles.component.ts
> + * This component allows the user to create a role.
Can we improve documentation here?

2021-09-09 07:44 UTC, svenvandescheur commented on frontend/zac-ui/libs/shared/ui/components/src/lib/elements/multiselect/multiselect.component.ts
>  @Component({
Can we start documenting these components as well when we work on them?

2021-09-09 07:44 UTC, svenvandescheur commented on frontend/zac-ui/libs/features/auth-profiles/src/lib/auth-profiles/add-auth-profile/add-auth-profile.component.ts
> +  formSubmit() {
I think it might be better to split this one up.

2021-09-09 07:44 UTC, svenvandescheur commented on frontend/zac-ui/libs/features/auth-profiles/src/lib/auth-profiles/add-auth-profile/add-auth-profile.component.html
> +<form [formGroup]="authProfileForm" (ngSubmit)="formSubmit()" *ngIf="caseTypes">
Can't we express this form as a `FieldConfiguration[]`?

2021-09-13 06:31 UTC, kelvincy commented on frontend/zac-ui/libs/features/auth-profiles/src/lib/auth-profiles/add-auth-profile/add-auth-profile.component.ts
> +  get authProfileNameControl() {
I understand your idea, but this form has a bit more complexity than normal. This form has input fields that can be added or deleted.

2021-09-13 06:31 UTC, kelvincy commented on frontend/zac-ui/libs/features/auth-profiles/src/lib/auth-profiles/add-auth-profile/add-auth-profile.component.html
> +<form [formGroup]="authProfileForm" (ngSubmit)="formSubmit()" *ngIf="caseTypes">
FieldConfiguration is not sufficient here

2021-09-13 07:08 UTC, svenvandescheur commented on frontend/zac-ui/libs/features/auth-profiles/src/lib/auth-profiles/add-auth-profile/add-auth-profile.component.ts
> +  get authProfileNameControl() {
I was more aiming towards de order of constructor, getter/setters, angular lifecycle, context processing, event handling and exception handing. It just an idea, but feel free to divert from this where needed.

2021-09-13 08:02 UTC, svenvandescheur approved these changes

2021-09-13 08:12 UTC, merged