Feature/add zaakobject url
GemeenteUtrecht/zaakafhandelcomponent pull request #441
Opened 2021-09-16 14:43 UTC by annashamray

2021-09-16 15:15 UTC, svenvandescheur commented
Part of: https://github.com/GemeenteUtrecht/zaakafhandelcomponent/pull/442

2021-09-17 08:40 UTC, annashamray commented
Part of: #442

2021-09-17 09:01 UTC, damm89 requested changes

2021-09-17 09:01 UTC, damm89 commented on backend/src/zac/core/zaakobjecten.py
> +        for zaakobject_url, item in object_items:
This will raise an exception if item on line 31 is not a tuple (which it shouldn't be if the typing hint is correct).

2021-09-17 15:41 UTC, merged