:sparkles: Add max_workers argument to index_zaken command
GemeenteUtrecht/zaakafhandelcomponent pull request #443
Opened 2021-09-20 11:41 UTC by damm89

This seems to be the most straightforward method of keeping memory use stable and in check while still having better performance than original (~200% faster but also >200% slower than keeping max_workers at 10).

2021-09-20 12:19 UTC, annashamray commented
@damm89 Could you also add charts with memory usage as is and with this change please?

2021-09-21 07:43 UTC, sergei-maertens requested changes

2021-09-21 07:43 UTC, sergei-maertens commented on backend/src/zac/elasticsearch/management/commands/index_zaken.py
> +        self.max_workers = options.get("max_workers", 4)
you can move the default to the `add_argument` call itself

2021-09-21 15:14 UTC, annashamray approved these changes
Let's try decreasing workers number and see what happens

2021-09-28 08:19 UTC, sergei-maertens approved these changes

2021-09-28 08:19 UTC, merged