Feature/contezza documents
GemeenteUtrecht/zaakafhandelcomponent pull request #481
Opened 2021-11-03 11:08 UTC by wasyllopatka

contezza-documentlist web-element updated.

2021-11-04 11:35 UTC, svenvandescheur reviewed
Looks good to me, I would like to know how we would deal with various environments and preferably have a single source of truth for these kind of settings.

2021-11-04 11:35 UTC, svenvandescheur commented on frontend/zac-ui/libs/features/contezza-document-search/src/app.config.json
> +  "ALFRESCO_PREVIEW_URL": "https://alfresco.cg-intern.ont.utrecht.nl"
How do we deal with different environments like production?

2021-11-04 11:35 UTC, svenvandescheur commented on frontend/zac-ui/proxy.conf.js
> +    target: 'https://alfresco-tezza.aks.utrechtproeftuin.nl',
How do we deal with different environments?

2021-11-04 11:35 UTC, svenvandescheur commented on ingress/default.conf.template
> +        proxy_pass https://alfresco.cg-intern.ont.utrecht.nl;
How do we deal with different environments?

2021-11-04 15:17 UTC, wasyllopatka commented on frontend/zac-ui/libs/features/contezza-document-search/src/app.config.json
> +  "ALFRESCO_PREVIEW_URL": "https://alfresco.cg-intern.ont.utrecht.nl"
Hi Sven, thank u. Values in app.config.json may by overriden on start docker container with variables.

2021-11-04 15:17 UTC, wasyllopatka commented on frontend/zac-ui/proxy.conf.js
> +    target: 'https://alfresco-tezza.aks.utrechtproeftuin.nl',
'proxy.conf.json' is used only in development mode. So, this is not necessary.

2021-11-04 15:17 UTC, wasyllopatka commented on ingress/default.conf.template
> +        proxy_pass https://alfresco.cg-intern.ont.utrecht.nl;
Here we can use variable instead of hardcoded url, e.g. 'proxy_pass ALFRESCO_URL;'

2021-11-04 15:19 UTC, svenvandescheur commented on ingress/default.conf.template
> +        proxy_pass https://alfresco.cg-intern.ont.utrecht.nl;
Is that currently already possible or de we still need to implement this?

2021-11-04 15:19 UTC, svenvandescheur commented on frontend/zac-ui/libs/features/contezza-document-search/src/app.config.json
> +  "ALFRESCO_PREVIEW_URL": "https://alfresco.cg-intern.ont.utrecht.nl"
Is that currently already possible or de we still need to implement this?

2021-11-04 16:19 UTC, wasyllopatka commented on frontend/zac-ui/libs/features/contezza-document-search/src/app.config.json
> +  "ALFRESCO_PREVIEW_URL": "https://alfresco.cg-intern.ont.utrecht.nl"
We still need to implement this.

2021-11-04 16:42 UTC, wasyllopatka commented on ingress/default.conf.template
> +        proxy_pass https://alfresco.cg-intern.ont.utrecht.nl;
I have this already implemented.

2021-11-05 09:33 UTC, sergei-maertens commented on frontend/zac-ui/libs/features/contezza-document-search/src/app.config.json
> +  "ALFRESCO_PREVIEW_URL": "https://alfresco.cg-intern.ont.utrecht.nl"
This is crucial for when we deploy the app to ACC environment too (which should happen Soon :tm: )

2021-11-05 09:50 UTC, sergei-maertens requested changes
One endpoint bug spotted, one question :)

2021-11-05 09:50 UTC, sergei-maertens commented on frontend/zac-ui/libs/features/zaak-detail/src/lib/documenten/documenten.service.ts
> +    return this.http.Patch<any>(encodeURI(`/api/core/cases/${bronorganisatie}/${identificatie}/document`), formData);
This endpoint no longer takes `bronorganisatie` or `identificatie` parameters, see https://zac.cg-intern.ont.utrecht.nl/api/docs/#operation/core_cases_document_partial_update

Instead, the `zaak` URL in the request body is required.

2021-11-05 09:50 UTC, sergei-maertens commented on ingress/Dockerfile
> +    ACS_PROXY_URL=https://alfresco.cg-intern.ont.utrecht.nl
Is this (proxy) needed for production deployment as well or only for development?

The ingress setup in this repo is not used in the Kubernetes deployments - this is only for local full-stack environments and I'm trying to estimate the impact.

2021-11-05 09:52 UTC, sergei-maertens commented
@wasyllopatka it's not clear from the code to me, but how does the end-user in the ZAC now authenticate to Alfresco?

2021-11-05 10:07 UTC, wasyllopatka commented on frontend/zac-ui/libs/features/zaak-detail/src/lib/documenten/documenten.service.ts
> +    return this.http.Patch<any>(encodeURI(`/api/core/cases/${bronorganisatie}/${identificatie}/document`), formData);
We do not use this endpoint for 'contezza-documentlist'.
But yes, it also has to be adjusted in the app.

2021-11-05 10:11 UTC, wasyllopatka commented
> @wasyllopatka it's not clear from the code to me, but how does the end-user in the ZAC now authenticate to Alfresco?

If user is not authenticated, he will get dialog to login to Alfresco.

2021-11-05 10:43 UTC, sergei-maertens commented on frontend/zac-ui/libs/features/contezza-document-search/src/app.config.json
> +  "ALFRESCO_PREVIEW_URL": "https://alfresco.cg-intern.ont.utrecht.nl"
I am coordinating with Tahir about this - we might solve this at the infrastructure level so that `$zacDomain/alfresco/` is provided.

We don't deploy dynamic nginx images (though the entrypoint with find/replace and/or envsubst is a possible fallback solution)

2021-11-05 10:44 UTC, sergei-maertens commented on frontend/zac-ui/libs/features/zaak-detail/src/lib/documenten/documenten.service.ts
> +    return this.http.Patch<any>(encodeURI(`/api/core/cases/${bronorganisatie}/${identificatie}/document`), formData);
I'm asking Sven to follow up on this!

2021-11-23 13:19 UTC, sergei-maertens approved these changes
I think this is okay for our needs? I have no idea if this is still blocked for merge or not though.

2021-11-23 13:33 UTC, merged