Update/bag api
GemeenteUtrecht/zaakafhandelcomponent pull request #540
Opened 2021-12-28 11:40 UTC by damm89

2021-12-28 17:25 UTC, annashamray approved these changes
Could you please add some documentation about Kadaster API, at least:
* the links to documentation and/or OAS for both BAG API and Location server 
* a couple of words how we use it
* examples of test data in the test API

it will help a lot!

2021-12-28 17:25 UTC, annashamray commented on backend/src/zac/contrib/kadaster/decorators.py
> +def catch_httperror(func: callable):
Nice decorators!

2022-01-06 16:10 UTC, svenvandescheur commented
@kelvincy wil jij de frontend reviewen?

2022-01-10 11:17 UTC, kelvincy requested changes
Looks fine overall, just a small comment about the zoom on the chart.

2022-01-10 11:17 UTC, kelvincy commented on frontend/zac-ui/libs/features/zaak-detail/src/lib/zaak-map/zaak-map.component.scss
> +  padding: 0 50px;
This is blocking the zoom functionality on the map

2022-01-11 10:18 UTC, kelvincy approved these changes

2022-01-11 11:10 UTC, merged