#1232 groepsactiviteit werkvoorraad
GemeenteUtrecht/zaakafhandelcomponent pull request #562
Opened 2022-01-28 10:31 UTC by kelvincy

2022-02-07 16:33 UTC, damm89 commented
Fixes https://github.com/GemeenteUtrecht/ZGW/issues/1232

2022-02-08 14:13 UTC, svenvandescheur requested changes

2022-02-08 14:13 UTC, svenvandescheur commented on frontend/zac-ui/libs/features/workstack/src/lib/features-workstack.component.html
> +                  {{groupActivity.zaak.identificatie}}: {{groupActivity.activities[0].name}}
Weten we zeker dat groupActivity.activities[0] bestaat?

2022-02-08 14:18 UTC, kelvincy commented on frontend/zac-ui/libs/features/workstack/src/lib/features-workstack.component.html
> +                  {{groupActivity.zaak.identificatie}}: {{groupActivity.activities[0].name}}
ja altijd maar 1 item in de array

2022-02-08 14:28 UTC, svenvandescheur approved these changes

2022-02-08 14:38 UTC, merged