Extended the BPR feature to allow for extra information to be pulled in
GemeenteUtrecht/zaakafhandelcomponent pull request #67
Opened 2020-08-31 09:54 UTC by damm89

2020-09-01 09:25 UTC, annashamray commented
@damm89 Could you link the issue with requirements for this PR?

2020-09-01 11:07 UTC, annashamray requested changes
Looks good! I have a couple of remarks mostly about using `zds_client` features and that's it

2020-09-01 11:07 UTC, annashamray commented on src/zac/contrib/brp/tests/test_brp_api.py
> +class BrpApiViewTests(APITestCase):
Could you also add a happy flow test here?

2020-09-01 11:07 UTC, annashamray commented on src/zac/contrib/brp/tests/test_brp_api.py
> +        self.assertEqual(result.geboorteland, "Nederland")
Could you also add an assertion for mock request query params?

2020-09-01 11:07 UTC, annashamray commented on src/zac/contrib/brp/tests/test_brp_api.py
> +class BrpApiViewTests(APITestCase):
Could you also add an assertion for error messages for these tests?

2020-09-01 11:26 UTC, damm89 commented on requirements/ci.txt
>  idna==2.8                 # via -r requirements/base.txt, requests, yarl
Thanks for the great tip!

2020-09-01 11:28 UTC, damm89 commented on requirements/dev.txt
> -black==19.10b0            # via -r requirements/dev.in
Will do

2020-09-01 13:12 UTC, SilviaAmAm commented on src/zac/contrib/brp/api.py
> +def call_client(url: str, doelbinding: Optional[str]=None):
Missing the type-hint for the return :)

2020-09-02 11:32 UTC, damm89 commented on src/zac/contrib/brp/api.py
> +def call_client(url: str, doelbinding: Optional[str] = None):
Please check update.

2020-09-02 11:33 UTC, damm89 commented on src/zac/contrib/brp/api.py
> +    url = urljoin(base_url, rel_url)
Solved for now I think

2020-09-02 11:33 UTC, damm89 commented on src/zac/contrib/brp/api.py
> +    req.prepare_url(url, params)
""

2020-09-02 11:33 UTC, damm89 commented on src/zac/core/api/views.py
> +            )
Changed it to lists. I'm not sure it matters performance wise but it certainly looks more readable.

2020-09-02 11:34 UTC, damm89 commented on src/zac/contrib/brp/tests/test_brp_api.py
> +class BrpApiViewTests(APITestCase):
Could you specify?

2020-09-02 11:35 UTC, damm89 commented on src/zac/contrib/brp/tests/test_brp_api.py
> +        self.assertEqual(result.geboorteland, "Nederland")
I think the assertion that the result exclusively includes the results from the parameters mentioned in the request_params implicitly shows that query_params are passed, right?

2020-09-02 11:35 UTC, damm89 commented on src/zac/contrib/brp/tests/test_brp_api.py
> +class BrpApiViewTests(APITestCase):
See update

2020-09-02 11:35 UTC, damm89 commented on src/zac/contrib/brp/api.py
> +def call_client(url: str, doelbinding: Optional[str]=None):
See update

2020-09-02 14:48 UTC, annashamray commented on src/zac/contrib/brp/tests/test_brp_api.py
> +class BrpApiViewTests(APITestCase):
Could you include the test that if all params are specified correctly, the response has 200 status and has a json and `fetch_extrainfo_np` function was executed (which can be mocked, for example)

2020-09-03 12:44 UTC, annashamray commented on src/zac/contrib/brp/tests/test_brp_api.py
> +        self.assertEqual(result.geboorteland, "Nederland")
yeah, it also works.

2020-09-03 12:45 UTC, annashamray approved these changes

2020-09-04 08:01 UTC, merged

2020-09-07 12:29 UTC, sergei-maertens commented on src/zac/core/api/views.py
> +            )
This would _probably_ be handled better with django-filters (and input validation there) or by having an input serializer that handles the validation. Both of those would allow you to declare the valid fields and mark the fields as required/optional, plus you get the `serializer.is_valid(raise_exception=True)` for standardized error responses back.