Feature/create zaak zac
GemeenteUtrecht/zaakafhandelcomponent pull request #684
Opened 2022-06-21 09:55 UTC by damm89

2022-06-21 09:55 UTC, damm89 commented on backend/src/zac/core/api/views.py
> +    # authentication_classes = (authentication.SessionAuthentication,)
```suggestion
    authentication_classes = (authentication.SessionAuthentication,)
```

2022-07-12 08:26 UTC, svenvandescheur requested changes
Few remarks

2022-07-13 08:38 UTC, kelvincy commented on frontend/zac-ui/libs/features/zaak-detail/src/lib/actions/keten-processen/configuration-components/start-process/role-step/role-step.component.html
> +      <gu-input
yes, still used

2022-07-13 08:38 UTC, kelvincy commented on frontend/zac-ui/libs/features/start-case/src/lib/features-start-case.component.ts
> +  getForm(zaak: Zaak = null): FieldConfiguration[] {
yes, still used

2022-07-13 08:41 UTC, merged