[WIP] :sparkles: add zaak behandelaars into 403 view context
GemeenteUtrecht/zaakafhandelcomponent pull request #70
Opened 2020-09-08 12:12 UTC by annashamray

fixes https://github.com/GemeenteUtrecht/zaakafhandelcomponent/issues/65

2020-09-14 10:15 UTC, sergei-maertens requested changes
In general okay for happy flow, but note the permissions-related remarks - that could be a security regression!

In general, functionality wise, the following remarks:

* the current flow is that a Zaak must have "behandelaars" to be able to _request_ access. That's annoying for the requester, as it seems like it's their fault they can't request access. The requesting of access should always be possible, we can tackle who can grant it later if there's no suitable person.

* The 'zaak-detail' page/template has the side-nav to link to access requests, but there's no indication if there are any. If the count is non-zero, probably a good idea to display the count. Or, a toast/notification bar on top of the page saying that there are access requests pending would be a good visual indicator. This information (and the menu entry) should be limited to people who can grant access. (Probably a good idea to define a permission/rules predicate to check if a user can grant access or not, so that we can extend on this later).

2020-09-14 10:15 UTC, sergei-maertens commented on src/zac/core/templates/core/zaak_access_requests.html
> +        Access requests for "{{ zaak.zaaktype.omschrijving }}"-zaak
Mark this translatable please

2020-09-14 10:15 UTC, sergei-maertens commented on src/zac/core/templates/core/zaak_access_requests.html
> +    {{ formset.non_form_errors }}
Should be wrapped in appropriate widget :)

2020-09-14 10:15 UTC, sergei-maertens commented on src/zac/core/templates/core/zaak_access_requests.html
> +                    {{  form.non_field_errors }}
this renders as an `<ul>` by default, which is invalid markup inside of a `<tr>` - you'll need to do some more error processing for formsets.

2020-09-14 10:15 UTC, sergei-maertens commented on src/zac/core/tests/test_access_requests.py
> +@patch("zac.core.forms.send_mail")
not needed - django replaces the mail backend automatically and you can use `django.core.mail.outbox` to inspect the mails being sent.

2020-09-14 10:15 UTC, sergei-maertens commented on src/zac/core/views/zaken.py
> +        return find_zaak(**self.request.resolver_match.kwargs)
```suggestion
        return find_zaak(**self.kwargs)
```
Bit more consistent with the other views and this uses the top-level API instead of request resolver internals.

2020-09-14 10:15 UTC, sergei-maertens commented on src/zac/core/views/zaken.py
> +        result = self.request.POST["submit"]
input is not validated, so I can now POST any value for `submit`, which will be saved in the DB and then the admin will not be able to display the proper option. Edge case, but still - always validate all your inputs.

2020-09-14 10:15 UTC, sergei-maertens commented on src/zac/templates/403.html
> +        You can <a href="{% url 'core:access-request-create' bronorganisatie=zaak_kwargs.bronorganisatie identificatie=zaak_kwargs.identificatie %}">request access</a> for this page
Translations... :)

2020-09-14 10:15 UTC, sergei-maertens commented on src/zac/templates/index.html
> +            <a href="#work-access-requests">Access requests ({{ access_requests|length }})</a>
translations

2020-09-14 10:15 UTC, sergei-maertens commented on src/zac/utils/views.py
> +    if request.resolver_match.url_name == "zaak-detail" and request.user:
```suggestion
    if request.resolver_match.url_name == "zaak-detail" and request.user.is_authenticated:
```

2020-09-17 15:40 UTC, annashamray reviewed
specific permission `zaken_handle_access` is added.
But I have a couple of questions about navigation menu formatting:
* should other navigation items also show the counter (like activiteiten)? 
* should I implement the same logic for dashboard (werkvoorraad) and hide access request tab if user doesn't have `zaken_handle_access` permission?

2020-09-17 15:40 UTC, annashamray commented on src/zac/accounts/models.py
> +        ).exists()
this snippet is moved to `has_temporary_access` rule predicate

2020-09-21 13:20 UTC, sergei-maertens commented on src/zac/core/rules.py
> +    return _generic_zaakpermission(user, zaak, zaken_inzien)
`Optional` is correct, but the `_has_permission_key(zaken_set_result.name, user)` is wrong, should be `_has_permission_key(zaken_inzien.name, user)` I think.

2020-09-21 13:24 UTC, sergei-maertens commented
> should other navigation items also show the counter (like activiteiten)?

No - we currently have that on the button on the top right, but we'll revisit probably at some point.

> should I implement the same logic for dashboard (werkvoorraad) and hide access request tab if user doesn't have zaken_handle_access permission?

Seems like a lot of work for something that doesn't really sit in the way if the list just stays empty.

2020-09-21 14:57 UTC, merged