:heavy_plus_sign: Add modal to retrieve extra BRP data
GemeenteUtrecht/zaakafhandelcomponent pull request #77
Opened 2020-09-15 07:24 UTC by kelvincy

2020-09-15 14:40 UTC, sergei-maertens requested changes
Great work!

* Checked http://localhost:8000/core/zaken/002220647/ZAAK-2020-0000004015/ as example - and a clickable vs. non-clickable betrokkene row have different paddings which looks a bit weird. Can we fix that? Additionally, looks like having the name be 50% of the width is too much, and the 'Type' column too little, so there's some tweaking in order there too (1920x1080 screen resolution).

* Checkboxes look nice!

* In the modal to request extra details, I'm missing the form label indication that fields are required. Right now you see that the button is disabled, but it's not clear _why_. The existing inputs/labels/wrappers provide that functionality already.

* Noticed the backend API call seems to take a long time (3.53s), but after second call it was clear this was because the API spec wasn't cached yet (740ms)

* Accessibility - the form modal closes on ESC, the results modal does not.

2020-09-15 14:40 UTC, sergei-maertens commented on src/zac/js/components/forms/Utils.js
> +        className += ' input--invalid';
could benefit from `classnames` as well

2020-09-15 14:40 UTC, sergei-maertens commented on src/zac/sass/components/_result.scss
> +}
```suggestion
@import "../lib/bem";

.result {
  margin-bottom: 1rem;

  @include element("title") {
    margin: 0 0 3px 0;
    font-size: 1rem;
  }

  @include element("value") {
    margin: 0;
  }
}

.subresult {
  @include element("title") {
    font-weight: bold;
    display: inline-block;
    margin: 0 0.4rem 0 0;
    &:after {
      content: ':'
    }
  }

  @include element("value") {
    margin: 0;
    display: inline-block;
  }

  @include element("row") {
    margin-left: 2rem;
    margin-bottom: 2rem;
  }
}
```

this mixin ensures that the resulting CSS selector is `.block .block__element` rather than `.block__element` - the latter makes it possible to write markup with elements without a parent block. The strict CSS enforces proper markup/class names structure.

2020-09-15 14:40 UTC, sergei-maertens commented on src/zac/sass/components/forms/_checkbox-select.scss
> +    &__inner {
`.block__element__subelement` is not proper BEM, any chance you can restructure this?

See also https://nl-design-system.gitlab.io/nl-design-system/componenten/checkbox/index.html please - so far we've been trying to stay a bit consistent with NLDS

2020-09-15 14:40 UTC, sergei-maertens commented on src/zac/sass/components/forms/_textarea.scss
> +.textarea {
I know there is a `.input__control--textarea`, defined in `_input.scss` taken from the NLDS - any chance we can re-use that to keep the styles consistent?

2020-09-17 07:00 UTC, kelvincy commented
@sergei-maertens the requested have been fixed.

2020-09-17 09:02 UTC, sergei-maertens commented on src/zac/js/components/betrokkenen/BetrokkenenForm.js
> +            method: 'GET',
Discussion on Slack about whether this should be GET or POST

2020-09-17 09:21 UTC, sergei-maertens requested changes
The sass components for forms worry me a bit.

I don't think that the current forms are ideal, but it looks like we're now adding conflicting alternative implementations/stylings that are impacting other forms (such as the login form).

Unfortunately we don't have a component library (yet) :(

2020-09-17 09:21 UTC, sergei-maertens commented on src/zac/sass/components/forms/_textarea.scss
> +}
this conflicts with/overwrites `src/zac/sass/components/forms/_inputs.scss`:

```scss
.input {
  border: 0;
  margin-bottom: 1em;
  padding: 0;
  position: relative;

  @include element('control') {
    border: 0;
    box-shadow: none;
    display: inline-block;
    font-size: 1.1rem;
    margin-right: 2rem;
    min-width: 0;
    width: 100%;

    @include modifier('text') {
      background: #fff;
      border: solid 1px #eee;
      border-radius: 0;
      color: $color-text;
      font: inherit;
      font-size: 1.4rem;
      overflow: visible;
      padding: 0.5rem 1rem;

      &:focus {
        box-shadow: none;
        outline: 2px solid $color-secondary;
      }
    }
  }
}
```

additionally, the `--text` modifier is used for `<input type="text" />` while `--textarea` is used for textareas.

In short - the name of this sass module and the classnames confuse me a lot.

2020-09-18 08:17 UTC, kelvincy commented on src/zac/sass/components/forms/_textarea.scss
> +}
Fixed

2020-09-18 08:17 UTC, kelvincy commented on src/zac/js/components/betrokkenen/BetrokkenenForm.js
> +            method: 'GET',
Changed to POST!

2020-09-21 12:57 UTC, sergei-maertens approved these changes

2020-09-21 12:57 UTC, merged