Added feature that allows for end user to provide a review request wi…
GemeenteUtrecht/zaakafhandelcomponent pull request #85
Opened 2020-09-29 13:49 UTC by damm89

…th an explanatory note

GemeenteUtrecht/ZGW#547

2020-09-30 16:52 UTC, annashamray requested changes
Looks good (especially tests) but I have some concerns.

In the Michelle's issue she asks to add `toelichting` only for `Approval`
In this PR `toelichting` is added to both models - `ReviewRequest` and `Approval`, which was not specified in the requirements. But perhaps I misunderstood the issue. We can have a call to clear this out

2020-09-30 16:52 UTC, annashamray commented on src/zac/contrib/kownsl/data.py
> +    toelichting: str
if ZAAK has already some review requests without `toelichting` this will crush the page. Could you add a default value, please?

2020-09-30 16:52 UTC, annashamray commented on src/zac/contrib/kownsl/data.py
> +    toelichting: str
Could you add a default value, please?

2020-09-30 17:45 UTC, damm89 commented on src/zac/contrib/kownsl/data.py
> +    toelichting: str
You're right!

2020-09-30 17:45 UTC, damm89 commented on src/zac/contrib/kownsl/data.py
> +    toelichting: str
Yes :)

2020-10-01 17:06 UTC, annashamray approved these changes
I don't know why we haven't used grid before in this project, maybe @sergei-maertens could know it. Perhaps we can discuss and create some style guidelines for this project in the nearest future to make all forms consistent

2020-10-05 10:34 UTC, sergei-maertens approved these changes

2020-10-05 10:38 UTC, sergei-maertens commented
> I don't know why we haven't used grid before in this project

It's not supported by Internet Explorer, see https://caniuse.com/css-grid

I think IE is no longer used for demo's, so we should be fine now.

2020-10-05 10:40 UTC, sergei-maertens commented
Double checked, but because of the default values this can be merged before the Kownsl stuff is merged (it just means that if we deploy it now that the information is "lost")

2020-10-05 10:41 UTC, merged