[WIP] Specifying permissions on each informatieobjecttype
GemeenteUtrecht/zaakafhandelcomponent pull request #96
Opened 2020-10-16 09:47 UTC by SilviaAmAm

2020-10-20 16:06 UTC, sergei-maertens commented
To recap what was said on Slack - I tested quickly (and did run some chrome debugger inspections) how it looks in the user interface and this is indeed the direction it should go.

Styling wise there's a lot to gain, I'll take that on me probably or assign it to Kelvin. I haven't done a code-review yet to check complexity, which I'll do tomorrow.

2020-10-21 09:08 UTC, sergei-maertens requested changes

2020-10-21 09:08 UTC, sergei-maertens commented on src/zac/js/components/informatieobjecttype-forms/informatieobjecttype-form.js
> +        ).then(
You can also use `async/await` syntax to make this look like regular synchronous code, while still using promises under the hood:

```jsx
import {get} from '../../utils/fetch';

const IOTEndpoint = '/accounts/permission-sets/informatieobjecttypes';

const informatieobjectTypes = await get(IOTEndpoint, {catalogus: catalogUrl});
```

2020-10-21 09:08 UTC, sergei-maertens commented on src/zac/js/components/informatieobjecttype-forms/informatieobjecttype-form.js
> +class InformatieobjecttypePermissionForm extends React.Component {
In general, I see a lot of component state management here that is *probably* not needed.

React has two types of inputs: controlled v.s. uncontrolled. The former is what you mostly see in SPA, the latter is particularly suited to just getting the DOM in the shape necessary to submit to the backend. These essentially operate using the `value` or `defaultValue` prop on form components (see also https://scriptverse.academy/tutorials/reactjs-defaultvalue-value.html).

Long story short - if we make sure that everything is output into `defaultValue` by using the right props, the browser will actually do the heavy lifting for us. Checking a checkbox is exactly that, the browser knows the state of that. Changing a dropdown -> also essentially managed by the browser by default.

So I think we can get rid of most of the state management in these components and make them stateless (or whatever state is there, is there in the browser itself).

2020-10-23 10:45 UTC, SilviaAmAm commented on src/zac/js/components/informatieobjecttype-forms/formset.js
> +export { FormSet };
I wanted to control the data that goes into the extra forms: in the formset in `src/zac/js/components/formsets/FormSet.js` the extra forms are empty.

I made a new one mostly because I wasn't sure this was the right way to go and I didn't want to break other things in the process of trying it out :sweat_smile: But if it was okay then I'll to update the existing formset implementation.

2020-10-23 13:09 UTC, sergei-maertens commented on src/zac/js/components/informatieobjecttype-forms/formset.js
> +export { FormSet };
> I wanted to control the data that goes into the extra forms: in the formset in src/zac/js/components/formsets/FormSet.js the extra forms are empty.

hrm, I *think* you can actually control that by passing it as an extra Object in the regular `formData` array. For the backend, it doesn't matter if it's an `extra` form or not - it's all treated the same. What matters is the hidden `id` field, which determines if it's an update or a create.

2020-10-26 13:48 UTC, sergei-maertens requested changes
I'll to through the frontend myself for a bit, especially with regard to:

1. Using a single `FormSet` class and organizing things so that it's possible to do so
2. Seeing how much state I can remove and make the forms uncontrolled components.

2020-10-26 13:48 UTC, sergei-maertens commented on src/zac/accounts/api/views.py
> +            raise ValidationError
```suggestion
        catalogus_url_serializer.is_valid(raise_exception=True)
```

2020-10-26 13:48 UTC, sergei-maertens commented on src/zac/accounts/views.py
> +                permission_set=context["object"]
```suggestion
                permission_set=self.object
```
`self.object` is set at the beginning of the `def get` in `DetailView`. It's the result of `self.get_object()`. Pulling stuff from the context while it's available as a view attribute seems a bit backwards.

2020-10-26 13:48 UTC, sergei-maertens commented on src/zac/core/rules.py
> +from odf.office import Document
wrong auto-import?

2020-10-26 13:48 UTC, sergei-maertens commented on src/zac/core/views/utils.py
> +        document.informatieobjecttype.vertrouwelijkheidaanduiding
```suggestion
        document.vertrouwelijkheidaanduiding
```
The document itself has a VA - which is by default the value from the IOT, but may be overridden.

2020-10-26 13:48 UTC, sergei-maertens commented on src/zac/core/views/utils.py
> +def check_document_permissions(document: Document, user: User):
I'm expecting a performance hit from the amount of queries happening in there, especially if it's being looped in `filter_documenten_for_permissions`. However, let's first verify the correctness and then tackle performance.

2020-10-28 16:35 UTC, sergei-maertens commented
Ran the CI steps locally on machine because the Travis backlog is horrendous again... Everything passes now.

2020-10-28 16:35 UTC, sergei-maertens approved these changes

2020-10-28 16:36 UTC, merged