Feature/termijnbewaking review request
GemeenteUtrecht/zaakafhandelcomponent pull request #99
Opened 2020-10-21 16:21 UTC by kelvincy

2020-10-27 14:13 UTC, sergei-maertens requested changes

2020-10-27 14:13 UTC, sergei-maertens commented on src/zac/accounts/api/viewsets.py
> +            include = self.request.query_params.get("include", False)
Should be a django-filter implementation, pretty sure it has built in filter types for this.

2020-10-27 14:13 UTC, sergei-maertens commented on src/zac/core/forms.py
> +        deadline_old = date(1, 1, 1)
```suggestion
        deadline_old = date.today()
```
Deadlines should be in the future imo, so we can use a realistic base-line with today's date?

2020-10-27 14:13 UTC, sergei-maertens commented on src/zac/core/forms.py
> +                    ),
This does not work with translatable strings, as the 'template' contains a dynamic value. Please use placeholders - in general, f-strings are not suitable for translatable content.

```suggestion
                    _("Please select a date greater than {minimum_date}").format(minimum_date=deadline_old.strftime('%Y-%m-%d'))
```

2020-10-27 14:13 UTC, sergei-maertens commented on src/zac/core/forms.py
> +                    None,
```suggestion
                    "deadline",
```
You can attach the error directly to the form.deadline field instead of putting it in the `form.non_field_errors`

2020-10-27 14:13 UTC, sergei-maertens commented on src/zac/core/forms.py
> +                form_add_error(None, _("Please select at least 1 advisor."))
advisor/approver - seems to be context dependent, so I'd make this dynamic to provide the correct feedback. You can also attach the error to the `users` field of the form rather than putting it in the non-field errors.

2020-10-27 14:13 UTC, sergei-maertens commented on src/zac/core/forms.py
> +                form.add_error(None, _("Please select unique advisors."))
Similar remarks to the above.

2020-10-27 14:13 UTC, sergei-maertens commented on src/zac/core/forms.py
> +        )
Should be implemented in the `FormSet.clean` method, see https://docs.djangoproject.com/en/2.2/topics/forms/formsets/#custom-formset-validation

2020-10-27 15:13 UTC, damm89 commented on src/zac/accounts/api/tests/test_viewsets.py
> +        response = self.client.get(search_url)
Got it

2020-10-27 15:14 UTC, damm89 commented on src/zac/accounts/api/viewsets.py
> +            include = self.request.query_params.get("include", False)
Alright, will look at it and change it in the BPTL as well.

2020-10-27 15:17 UTC, damm89 commented on src/zac/core/forms.py
> +        )
Alright

2020-10-28 11:37 UTC, damm89 commented on src/zac/core/forms.py
> +                form_add_error(None, _("Please select at least 1 advisor."))
well, the current frontend doesn't allow for the extra forms to persist once submitted. Attaching it to the field of a non-existing form doesn't seem to have any real benefits?

2020-10-28 13:48 UTC, damm89 approved these changes

2020-10-28 13:58 UTC, sergei-maertens approved these changes

2020-10-28 13:59 UTC, sergei-maertens commented on src/zac/core/forms.py
> +                form_add_error(None, _("Please select at least 1 advisor."))
Hrm, current solution seems sufficient then. I think UI-wise there's something to gain, but it would be better suited to include that in the form-data that's passed to the frontend and I don't think we should delay this feature any longer because of that, it can easily be tackled later.

2020-10-28 14:02 UTC, sergei-maertens commented
Ok, verified the CI steps locally on my machine as the Travis build queue is massive again:

- [x] black ok
- [x] isort ok
- [x] docker build ok
- [x] tests pass

So, I'm merging this into develop.

2020-10-28 14:02 UTC, merged